/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  ExecutionRecord,
  PostApiV1TenantsTidSpacesSpaceIdExecutionsBody
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Admits one Execution for an Agent, atomically freezing its enabled Skill bindings to their exact current revisions plus a first eligible Attempt. The body carries only agentId; the Skill set is resolved server-side from durable bindings, never from caller input. The Idempotency-Key scopes the generic tenant/user replay, so a retry returns the original Execution rather than creating a second one. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/executions
 */
export const postApiV1TenantsTidSpacesSpaceIdExecutions = (
    tid: string,
    spaceId: string,
    postApiV1TenantsTidSpacesSpaceIdExecutionsBody: PostApiV1TenantsTidSpacesSpaceIdExecutionsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ExecutionRecord>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/executions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidSpacesSpaceIdExecutionsBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidSpacesSpaceIdExecutionsMutationKey = () => ['postApiV1TenantsTidSpacesSpaceIdExecutions'] as const;

export const getPostApiV1TenantsTidSpacesSpaceIdExecutionsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdExecutions>>, TError,PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdExecutions>>, TError,PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidSpacesSpaceIdExecutionsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdExecutions>>, PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationVariables> = (props) => {
          const {tid,spaceId,data} = props ?? {};

          return  postApiV1TenantsTidSpacesSpaceIdExecutions(tid,spaceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdExecutions>>>
    export type PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationBody = PostApiV1TenantsTidSpacesSpaceIdExecutionsBody
    export type PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationVariables = {tid: string;spaceId: string;data: PostApiV1TenantsTidSpacesSpaceIdExecutionsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/executions
 */
export const usePostApiV1TenantsTidSpacesSpaceIdExecutions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdExecutions>>, TError,PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdExecutions>>,
        TError,
        PostApiV1TenantsTidSpacesSpaceIdExecutionsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidSpacesSpaceIdExecutionsMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Reads a frozen Execution aggregate — execution, attempts (real states, starting eligible) and immutable skill bindings — by id, scoped to the caller's workspace. The snapshot is immutable and survives later binding disable/detach/revision change; no credential or signed URL is present. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/executions/:executionId
 */
export const getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId = (
    tid: string,
    spaceId: string,
    executionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ExecutionRecord>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/executions/${executionId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionIdQueryKey = (tid: string,
    spaceId: string,
    executionId: string,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}/executions/${executionId}`
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string,
    executionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionIdQueryKey(tid,spaceId,executionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>> = ({ signal }) => getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId(tid,spaceId,executionId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined && executionId !== null && executionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>>
export type GetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionIdQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    executionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    executionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    executionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/executions/:executionId
 */

export function useGetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    executionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdExecutionsExecutionId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSpaceIdExecutionsExecutionIdQueryOptions(tid,spaceId,executionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






