// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/errors.proto

// Internal control contract between Cloud (API Server, the authoritative persistence) and a
// Controller (a stateless coordination worker). Cloud is the server for every RPC; a Controller
// only dials out. Identities are opaque strings Cloud has already authorized: there are no
// tenant, user or membership fields at this boundary by design.

package controlpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Submission identity or record content conflicts with the durable record; retrying the same
	// call cannot succeed. Carried with ABORTED.
	ErrorCode_ERROR_CODE_CONFLICT ErrorCode = 1
	// The request itself is malformed. Carried with INVALID_ARGUMENT.
	ErrorCode_ERROR_CODE_INVALID_INPUT ErrorCode = 2
	// Persistence is temporarily unavailable; nothing was committed and the same submission may be
	// retried. Carried with UNAVAILABLE.
	ErrorCode_ERROR_CODE_UNAVAILABLE ErrorCode = 3
	// No durable record exists for the given identity. Carried with NOT_FOUND.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 4
	// The caller's lease epoch is not the current one; it must re-acquire before writing.
	// Carried with FAILED_PRECONDITION.
	ErrorCode_ERROR_CODE_STALE_CONTROLLER ErrorCode = 5
	// Another holder owns a valid lease. Carried with FAILED_PRECONDITION.
	ErrorCode_ERROR_CODE_LEASE_HELD ErrorCode = 6
	// The service principal is not allowed to perform this call. Carried with PERMISSION_DENIED.
	ErrorCode_ERROR_CODE_SERVICE_FORBIDDEN ErrorCode = 7
	// RetrievalCapability (Step 5B) error taxonomy — see the skill-retrieval-capability ADR D32.
	// Object storage is not configured; no capability can be minted and no proxy/fake URL is offered.
	// Carried with FAILED_PRECONDITION.
	ErrorCode_ERROR_CODE_SKILL_STORAGE_NOT_CONFIGURED ErrorCode = 8
	// The requested skill_revision_id is not among the execution's frozen bindings. Carried with
	// NOT_FOUND.
	ErrorCode_ERROR_CODE_SKILL_REVISION_NOT_BOUND ErrorCode = 9
	// The attempt is terminal (succeeded/failed/canceled/superseded) and must not mint a capability.
	// Carried with FAILED_PRECONDITION.
	ErrorCode_ERROR_CODE_SKILL_ATTEMPT_NOT_ELIGIBLE ErrorCode = 10
	// The requested object does not exist in storage; the caller must fail closed. Carried with
	// NOT_FOUND.
	ErrorCode_ERROR_CODE_SKILL_OBJECT_NOT_AVAILABLE ErrorCode = 11
	// Cloud could not produce a signed URL (provider error). Carried with UNAVAILABLE; retry after a
	// short wait.
	ErrorCode_ERROR_CODE_SKILL_SIGNING_FAILED ErrorCode = 12
	// A frozen revision carries an object_locator Cloud cannot parse into a logical key. Carried with
	// INTERNAL.
	ErrorCode_ERROR_CODE_SKILL_INVALID_LOCATOR ErrorCode = 13
	// The capability has expired; refresh or retry. Carried with FAILED_PRECONDITION.
	ErrorCode_ERROR_CODE_SKILL_EXPIRED_OR_RETRY_REQUIRED ErrorCode = 14
	// The (execution_id, attempt_id, skill_revision_id) authority chain does not verify. Carried with
	// NOT_FOUND so it is indistinguishable from an unknown record.
	ErrorCode_ERROR_CODE_SKILL_AUTHORIZATION_FAILED ErrorCode = 15
	// Transient control-plane failure; safe to retry. Carried with UNAVAILABLE.
	ErrorCode_ERROR_CODE_SKILL_TEMPORARY_CONTROL_PLANE_FAILURE ErrorCode = 16
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_CONFLICT",
		2:  "ERROR_CODE_INVALID_INPUT",
		3:  "ERROR_CODE_UNAVAILABLE",
		4:  "ERROR_CODE_NOT_FOUND",
		5:  "ERROR_CODE_STALE_CONTROLLER",
		6:  "ERROR_CODE_LEASE_HELD",
		7:  "ERROR_CODE_SERVICE_FORBIDDEN",
		8:  "ERROR_CODE_SKILL_STORAGE_NOT_CONFIGURED",
		9:  "ERROR_CODE_SKILL_REVISION_NOT_BOUND",
		10: "ERROR_CODE_SKILL_ATTEMPT_NOT_ELIGIBLE",
		11: "ERROR_CODE_SKILL_OBJECT_NOT_AVAILABLE",
		12: "ERROR_CODE_SKILL_SIGNING_FAILED",
		13: "ERROR_CODE_SKILL_INVALID_LOCATOR",
		14: "ERROR_CODE_SKILL_EXPIRED_OR_RETRY_REQUIRED",
		15: "ERROR_CODE_SKILL_AUTHORIZATION_FAILED",
		16: "ERROR_CODE_SKILL_TEMPORARY_CONTROL_PLANE_FAILURE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                           0,
		"ERROR_CODE_CONFLICT":                              1,
		"ERROR_CODE_INVALID_INPUT":                         2,
		"ERROR_CODE_UNAVAILABLE":                           3,
		"ERROR_CODE_NOT_FOUND":                             4,
		"ERROR_CODE_STALE_CONTROLLER":                      5,
		"ERROR_CODE_LEASE_HELD":                            6,
		"ERROR_CODE_SERVICE_FORBIDDEN":                     7,
		"ERROR_CODE_SKILL_STORAGE_NOT_CONFIGURED":          8,
		"ERROR_CODE_SKILL_REVISION_NOT_BOUND":              9,
		"ERROR_CODE_SKILL_ATTEMPT_NOT_ELIGIBLE":            10,
		"ERROR_CODE_SKILL_OBJECT_NOT_AVAILABLE":            11,
		"ERROR_CODE_SKILL_SIGNING_FAILED":                  12,
		"ERROR_CODE_SKILL_INVALID_LOCATOR":                 13,
		"ERROR_CODE_SKILL_EXPIRED_OR_RETRY_REQUIRED":       14,
		"ERROR_CODE_SKILL_AUTHORIZATION_FAILED":            15,
		"ERROR_CODE_SKILL_TEMPORARY_CONTROL_PLANE_FAILURE": 16,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_cloud_internal_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_ora_cloud_internal_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_errors_proto_rawDescGZIP(), []int{0}
}

// Classification attached to failed calls as a google.rpc.Status detail. The gRPC status code
// carries the primary classification (ABORTED, FAILED_PRECONDITION, INVALID_ARGUMENT, NOT_FOUND,
// PERMISSION_DENIED, UNAVAILABLE); the enum refines it so callers branch on neither message text
// nor HTTP-era string codes. Both are produced in one place on the Cloud side and never disagree.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=ora.cloud.internal.v1.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_ora_cloud_internal_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

var File_ora_cloud_internal_v1_errors_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\"ora/cloud/internal/v1/errors.proto\x12\x15ora.cloud.internal.v1\"C\n" +
	"\vErrorDetail\x124\n" +
	"\x04code\x18\x01 \x01(\x0e2 .ora.cloud.internal.v1.ErrorCodeR\x04code*\xfa\x04\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\x01\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_INPUT\x10\x02\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12\x1f\n" +
	"\x1bERROR_CODE_STALE_CONTROLLER\x10\x05\x12\x19\n" +
	"\x15ERROR_CODE_LEASE_HELD\x10\x06\x12 \n" +
	"\x1cERROR_CODE_SERVICE_FORBIDDEN\x10\a\x12+\n" +
	"'ERROR_CODE_SKILL_STORAGE_NOT_CONFIGURED\x10\b\x12'\n" +
	"#ERROR_CODE_SKILL_REVISION_NOT_BOUND\x10\t\x12)\n" +
	"%ERROR_CODE_SKILL_ATTEMPT_NOT_ELIGIBLE\x10\n" +
	"\x12)\n" +
	"%ERROR_CODE_SKILL_OBJECT_NOT_AVAILABLE\x10\v\x12#\n" +
	"\x1fERROR_CODE_SKILL_SIGNING_FAILED\x10\f\x12$\n" +
	" ERROR_CODE_SKILL_INVALID_LOCATOR\x10\r\x12.\n" +
	"*ERROR_CODE_SKILL_EXPIRED_OR_RETRY_REQUIRED\x10\x0e\x12)\n" +
	"%ERROR_CODE_SKILL_AUTHORIZATION_FAILED\x10\x0f\x124\n" +
	"0ERROR_CODE_SKILL_TEMPORARY_CONTROL_PLANE_FAILURE\x10\x10b\x06proto3"

var (
	file_ora_cloud_internal_v1_errors_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_errors_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_errors_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_errors_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_errors_proto_rawDesc), len(file_ora_cloud_internal_v1_errors_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_errors_proto_rawDescData
}

var file_ora_cloud_internal_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ora_cloud_internal_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ora_cloud_internal_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0),      // 0: ora.cloud.internal.v1.ErrorCode
	(*ErrorDetail)(nil), // 1: ora.cloud.internal.v1.ErrorDetail
}
var file_ora_cloud_internal_v1_errors_proto_depIdxs = []int32{
	0, // 0: ora.cloud.internal.v1.ErrorDetail.code:type_name -> ora.cloud.internal.v1.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_errors_proto_init() }
func file_ora_cloud_internal_v1_errors_proto_init() {
	if File_ora_cloud_internal_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_errors_proto_rawDesc), len(file_ora_cloud_internal_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ora_cloud_internal_v1_errors_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_errors_proto_depIdxs,
		EnumInfos:         file_ora_cloud_internal_v1_errors_proto_enumTypes,
		MessageInfos:      file_ora_cloud_internal_v1_errors_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_errors_proto = out.File
	file_ora_cloud_internal_v1_errors_proto_goTypes = nil
	file_ora_cloud_internal_v1_errors_proto_depIdxs = nil
}
