// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ora/cloud/internal/v1/executions.proto

package controlpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_ClaimWork_FullMethodName             = "/ora.cloud.internal.v1.ExecutionService/ClaimWork"
	ExecutionService_RecordDispatch_FullMethodName        = "/ora.cloud.internal.v1.ExecutionService/RecordDispatch"
	ExecutionService_TakeOverNodeEvent_FullMethodName     = "/ora.cloud.internal.v1.ExecutionService/TakeOverNodeEvent"
	ExecutionService_RecordQueriedResult_FullMethodName   = "/ora.cloud.internal.v1.ExecutionService/RecordQueriedResult"
	ExecutionService_GetDispatch_FullMethodName           = "/ora.cloud.internal.v1.ExecutionService/GetDispatch"
	ExecutionService_ListPendingDispatches_FullMethodName = "/ora.cloud.internal.v1.ExecutionService/ListPendingDispatches"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Durable coordination of Node executions, starting with the clone closed loop. Every call that
// changes state returns only after Cloud committed it, and each such call carries a caller-chosen
// `submission_id`: repeating a submission with identical content returns the original response
// without reapplying anything; the same identity with different content fails with ABORTED
// (CONFLICT). A lost reply is therefore retried with the same submission, never a new identity.
type ExecutionServiceClient interface {
	// Claims the oldest work item Cloud has accepted but no Controller has dispatched yet. Returns
	// no item when nothing is pending; ownership is decided here, not by a Watch signal.
	ClaimWork(ctx context.Context, in *ClaimWorkRequest, opts ...grpc.CallOption) (*ClaimWorkResponse, error)
	// Registers execution identity, target Node and full input before any Node sees the command.
	// Only after this succeeds may the Controller dispatch; the same execution with the same input
	// is idempotent, a different input conflicts.
	RecordDispatch(ctx context.Context, in *RecordDispatchRequest, opts ...grpc.CallOption) (*RecordDispatchResponse, error)
	// Commits an execution fact together with the exact receipt of the Node event that carried it.
	// Only after this succeeds may the Controller acknowledge that event sequence to the Node.
	TakeOverNodeEvent(ctx context.Context, in *TakeOverNodeEventRequest, opts ...grpc.CallOption) (*TakeOverNodeEventResponse, error)
	// Stores a Completed result learned by querying the Node. It records no receipt, so it never
	// authorizes an acknowledgement.
	RecordQueriedResult(ctx context.Context, in *RecordQueriedResultRequest, opts ...grpc.CallOption) (*RecordQueriedResultResponse, error)
	// Reads one registered execution; an unknown execution fails with NOT_FOUND, distinct from a
	// registered execution that has no result yet.
	GetDispatch(ctx context.Context, in *GetDispatchRequest, opts ...grpc.CallOption) (*GetDispatchResponse, error)
	// Lists registered executions without a result so a recovering or replacement worker resumes
	// the original executions instead of creating new ones.
	ListPendingDispatches(ctx context.Context, in *ListPendingDispatchesRequest, opts ...grpc.CallOption) (*ListPendingDispatchesResponse, error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) ClaimWork(ctx context.Context, in *ClaimWorkRequest, opts ...grpc.CallOption) (*ClaimWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimWorkResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ClaimWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) RecordDispatch(ctx context.Context, in *RecordDispatchRequest, opts ...grpc.CallOption) (*RecordDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordDispatchResponse)
	err := c.cc.Invoke(ctx, ExecutionService_RecordDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) TakeOverNodeEvent(ctx context.Context, in *TakeOverNodeEventRequest, opts ...grpc.CallOption) (*TakeOverNodeEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeOverNodeEventResponse)
	err := c.cc.Invoke(ctx, ExecutionService_TakeOverNodeEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) RecordQueriedResult(ctx context.Context, in *RecordQueriedResultRequest, opts ...grpc.CallOption) (*RecordQueriedResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordQueriedResultResponse)
	err := c.cc.Invoke(ctx, ExecutionService_RecordQueriedResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) GetDispatch(ctx context.Context, in *GetDispatchRequest, opts ...grpc.CallOption) (*GetDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDispatchResponse)
	err := c.cc.Invoke(ctx, ExecutionService_GetDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) ListPendingDispatches(ctx context.Context, in *ListPendingDispatchesRequest, opts ...grpc.CallOption) (*ListPendingDispatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingDispatchesResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ListPendingDispatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations must embed UnimplementedExecutionServiceServer
// for forward compatibility.
//
// Durable coordination of Node executions, starting with the clone closed loop. Every call that
// changes state returns only after Cloud committed it, and each such call carries a caller-chosen
// `submission_id`: repeating a submission with identical content returns the original response
// without reapplying anything; the same identity with different content fails with ABORTED
// (CONFLICT). A lost reply is therefore retried with the same submission, never a new identity.
type ExecutionServiceServer interface {
	// Claims the oldest work item Cloud has accepted but no Controller has dispatched yet. Returns
	// no item when nothing is pending; ownership is decided here, not by a Watch signal.
	ClaimWork(context.Context, *ClaimWorkRequest) (*ClaimWorkResponse, error)
	// Registers execution identity, target Node and full input before any Node sees the command.
	// Only after this succeeds may the Controller dispatch; the same execution with the same input
	// is idempotent, a different input conflicts.
	RecordDispatch(context.Context, *RecordDispatchRequest) (*RecordDispatchResponse, error)
	// Commits an execution fact together with the exact receipt of the Node event that carried it.
	// Only after this succeeds may the Controller acknowledge that event sequence to the Node.
	TakeOverNodeEvent(context.Context, *TakeOverNodeEventRequest) (*TakeOverNodeEventResponse, error)
	// Stores a Completed result learned by querying the Node. It records no receipt, so it never
	// authorizes an acknowledgement.
	RecordQueriedResult(context.Context, *RecordQueriedResultRequest) (*RecordQueriedResultResponse, error)
	// Reads one registered execution; an unknown execution fails with NOT_FOUND, distinct from a
	// registered execution that has no result yet.
	GetDispatch(context.Context, *GetDispatchRequest) (*GetDispatchResponse, error)
	// Lists registered executions without a result so a recovering or replacement worker resumes
	// the original executions instead of creating new ones.
	ListPendingDispatches(context.Context, *ListPendingDispatchesRequest) (*ListPendingDispatchesResponse, error)
	mustEmbedUnimplementedExecutionServiceServer()
}

// UnimplementedExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) ClaimWork(context.Context, *ClaimWorkRequest) (*ClaimWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimWork not implemented")
}
func (UnimplementedExecutionServiceServer) RecordDispatch(context.Context, *RecordDispatchRequest) (*RecordDispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordDispatch not implemented")
}
func (UnimplementedExecutionServiceServer) TakeOverNodeEvent(context.Context, *TakeOverNodeEventRequest) (*TakeOverNodeEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeOverNodeEvent not implemented")
}
func (UnimplementedExecutionServiceServer) RecordQueriedResult(context.Context, *RecordQueriedResultRequest) (*RecordQueriedResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordQueriedResult not implemented")
}
func (UnimplementedExecutionServiceServer) GetDispatch(context.Context, *GetDispatchRequest) (*GetDispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDispatch not implemented")
}
func (UnimplementedExecutionServiceServer) ListPendingDispatches(context.Context, *ListPendingDispatchesRequest) (*ListPendingDispatchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPendingDispatches not implemented")
}
func (UnimplementedExecutionServiceServer) mustEmbedUnimplementedExecutionServiceServer() {}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_ClaimWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ClaimWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ClaimWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ClaimWork(ctx, req.(*ClaimWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_RecordDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).RecordDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_RecordDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).RecordDispatch(ctx, req.(*RecordDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_TakeOverNodeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeOverNodeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).TakeOverNodeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_TakeOverNodeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).TakeOverNodeEvent(ctx, req.(*TakeOverNodeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_RecordQueriedResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordQueriedResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).RecordQueriedResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_RecordQueriedResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).RecordQueriedResult(ctx, req.(*RecordQueriedResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_GetDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).GetDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_GetDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).GetDispatch(ctx, req.(*GetDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_ListPendingDispatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingDispatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ListPendingDispatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ListPendingDispatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ListPendingDispatches(ctx, req.(*ListPendingDispatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ora.cloud.internal.v1.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimWork",
			Handler:    _ExecutionService_ClaimWork_Handler,
		},
		{
			MethodName: "RecordDispatch",
			Handler:    _ExecutionService_RecordDispatch_Handler,
		},
		{
			MethodName: "TakeOverNodeEvent",
			Handler:    _ExecutionService_TakeOverNodeEvent_Handler,
		},
		{
			MethodName: "RecordQueriedResult",
			Handler:    _ExecutionService_RecordQueriedResult_Handler,
		},
		{
			MethodName: "GetDispatch",
			Handler:    _ExecutionService_GetDispatch_Handler,
		},
		{
			MethodName: "ListPendingDispatches",
			Handler:    _ExecutionService_ListPendingDispatches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ora/cloud/internal/v1/executions.proto",
}
