// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/executions.proto

package controlpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloneFailureReason int32

const (
	CloneFailureReason_CLONE_FAILURE_REASON_UNSPECIFIED          CloneFailureReason = 0
	CloneFailureReason_CLONE_FAILURE_REASON_SOURCE_UNAVAILABLE   CloneFailureReason = 1
	CloneFailureReason_CLONE_FAILURE_REASON_BRANCH_NOT_FOUND     CloneFailureReason = 2
	CloneFailureReason_CLONE_FAILURE_REASON_DESTINATION_CONFLICT CloneFailureReason = 3
	CloneFailureReason_CLONE_FAILURE_REASON_OPERATION_FAILED     CloneFailureReason = 4
)

// Enum value maps for CloneFailureReason.
var (
	CloneFailureReason_name = map[int32]string{
		0: "CLONE_FAILURE_REASON_UNSPECIFIED",
		1: "CLONE_FAILURE_REASON_SOURCE_UNAVAILABLE",
		2: "CLONE_FAILURE_REASON_BRANCH_NOT_FOUND",
		3: "CLONE_FAILURE_REASON_DESTINATION_CONFLICT",
		4: "CLONE_FAILURE_REASON_OPERATION_FAILED",
	}
	CloneFailureReason_value = map[string]int32{
		"CLONE_FAILURE_REASON_UNSPECIFIED":          0,
		"CLONE_FAILURE_REASON_SOURCE_UNAVAILABLE":   1,
		"CLONE_FAILURE_REASON_BRANCH_NOT_FOUND":     2,
		"CLONE_FAILURE_REASON_DESTINATION_CONFLICT": 3,
		"CLONE_FAILURE_REASON_OPERATION_FAILED":     4,
	}
)

func (x CloneFailureReason) Enum() *CloneFailureReason {
	p := new(CloneFailureReason)
	*p = x
	return p
}

func (x CloneFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloneFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_cloud_internal_v1_executions_proto_enumTypes[0].Descriptor()
}

func (CloneFailureReason) Type() protoreflect.EnumType {
	return &file_ora_cloud_internal_v1_executions_proto_enumTypes[0]
}

func (x CloneFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloneFailureReason.Descriptor instead.
func (CloneFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{0}
}

// Persistent Node identity plus the incarnation that produced a fact. Historical incarnations
// are kept as recorded; they are never rewritten to the current session.
type NodeIdentity struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeIncarnationId string                 `protobuf:"bytes,2,opt,name=node_incarnation_id,json=nodeIncarnationId,proto3" json:"node_incarnation_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeIdentity) GetNodeIncarnationId() string {
	if x != nil {
		return x.NodeIncarnationId
	}
	return ""
}

type CloneSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTPS or SSH repository URL. Checkout paths belong to the Node, never to the caller.
	Repository    string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch        string `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneSpec) Reset() {
	*x = CloneSpec{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneSpec) ProtoMessage() {}

func (x *CloneSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneSpec.ProtoReflect.Descriptor instead.
func (*CloneSpec) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{1}
}

func (x *CloneSpec) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *CloneSpec) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

// One exact frozen SkillRevision reference carried in a dispatch descriptor (Execution Snapshot
// ADR D4 / plan §17.1). It mirrors the immutable ExecutionSkillBinding content identity so the
// Controller and Node never re-resolve mutable Skill state. The retrieval capability is a separate
// later layer and deliberately not carried here.
type SkillBundleRef struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SkillRevisionId      string                 `protobuf:"bytes,1,opt,name=skill_revision_id,json=skillRevisionId,proto3" json:"skill_revision_id,omitempty"`
	ContentDigest        string                 `protobuf:"bytes,2,opt,name=content_digest,json=contentDigest,proto3" json:"content_digest,omitempty"`
	SizeBytes            int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	PackageFormat        string                 `protobuf:"bytes,4,opt,name=package_format,json=packageFormat,proto3" json:"package_format,omitempty"`
	PackageFormatVersion int32                  `protobuf:"varint,5,opt,name=package_format_version,json=packageFormatVersion,proto3" json:"package_format_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SkillBundleRef) Reset() {
	*x = SkillBundleRef{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillBundleRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillBundleRef) ProtoMessage() {}

func (x *SkillBundleRef) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillBundleRef.ProtoReflect.Descriptor instead.
func (*SkillBundleRef) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{2}
}

func (x *SkillBundleRef) GetSkillRevisionId() string {
	if x != nil {
		return x.SkillRevisionId
	}
	return ""
}

func (x *SkillBundleRef) GetContentDigest() string {
	if x != nil {
		return x.ContentDigest
	}
	return ""
}

func (x *SkillBundleRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SkillBundleRef) GetPackageFormat() string {
	if x != nil {
		return x.PackageFormat
	}
	return ""
}

func (x *SkillBundleRef) GetPackageFormatVersion() int32 {
	if x != nil {
		return x.PackageFormatVersion
	}
	return 0
}

// A skill-bearing execution kind: the exact frozen Skill revisions an Agent execution runs with.
type SkillRunSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillBundles  []*SkillBundleRef      `protobuf:"bytes,1,rep,name=skill_bundles,json=skillBundles,proto3" json:"skill_bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillRunSpec) Reset() {
	*x = SkillRunSpec{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRunSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRunSpec) ProtoMessage() {}

func (x *SkillRunSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRunSpec.ProtoReflect.Descriptor instead.
func (*SkillRunSpec) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{3}
}

func (x *SkillRunSpec) GetSkillBundles() []*SkillBundleRef {
	if x != nil {
		return x.SkillBundles
	}
	return nil
}

// Full execution input as dispatched; extended with new oneof members as further execution kinds
// join the loop.
type ExecutionInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Spec:
	//
	//	*ExecutionInput_Clone
	//	*ExecutionInput_SkillRun
	Spec          isExecutionInput_Spec `protobuf_oneof:"spec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionInput) Reset() {
	*x = ExecutionInput{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionInput) ProtoMessage() {}

func (x *ExecutionInput) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionInput.ProtoReflect.Descriptor instead.
func (*ExecutionInput) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionInput) GetSpec() isExecutionInput_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ExecutionInput) GetClone() *CloneSpec {
	if x != nil {
		if x, ok := x.Spec.(*ExecutionInput_Clone); ok {
			return x.Clone
		}
	}
	return nil
}

func (x *ExecutionInput) GetSkillRun() *SkillRunSpec {
	if x != nil {
		if x, ok := x.Spec.(*ExecutionInput_SkillRun); ok {
			return x.SkillRun
		}
	}
	return nil
}

type isExecutionInput_Spec interface {
	isExecutionInput_Spec()
}

type ExecutionInput_Clone struct {
	Clone *CloneSpec `protobuf:"bytes,1,opt,name=clone,proto3,oneof"`
}

type ExecutionInput_SkillRun struct {
	SkillRun *SkillRunSpec `protobuf:"bytes,2,opt,name=skill_run,json=skillRun,proto3,oneof"`
}

func (*ExecutionInput_Clone) isExecutionInput_Spec() {}

func (*ExecutionInput_SkillRun) isExecutionInput_Spec() {}

type CloneReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneReady) Reset() {
	*x = CloneReady{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneReady) ProtoMessage() {}

func (x *CloneReady) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneReady.ProtoReflect.Descriptor instead.
func (*CloneReady) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{5}
}

func (x *CloneReady) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CloneReady) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type CloneFailed struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason CloneFailureReason     `protobuf:"varint,1,opt,name=reason,proto3,enum=ora.cloud.internal.v1.CloneFailureReason" json:"reason,omitempty"`
	// Directory the Node retained for inspection, when it kept one.
	RetainedPath  *string `protobuf:"bytes,2,opt,name=retained_path,json=retainedPath,proto3,oneof" json:"retained_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneFailed) Reset() {
	*x = CloneFailed{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneFailed) ProtoMessage() {}

func (x *CloneFailed) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneFailed.ProtoReflect.Descriptor instead.
func (*CloneFailed) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{6}
}

func (x *CloneFailed) GetReason() CloneFailureReason {
	if x != nil {
		return x.Reason
	}
	return CloneFailureReason_CLONE_FAILURE_REASON_UNSPECIFIED
}

func (x *CloneFailed) GetRetainedPath() string {
	if x != nil && x.RetainedPath != nil {
		return *x.RetainedPath
	}
	return ""
}

// Terminal fact reported by a Node for one execution.
type ExecutionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Node  *NodeIdentity          `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ExecutionResult_CloneReady
	//	*ExecutionResult_CloneFailed
	Outcome       isExecutionResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionResult) GetNode() *NodeIdentity {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ExecutionResult) GetOutcome() isExecutionResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ExecutionResult) GetCloneReady() *CloneReady {
	if x != nil {
		if x, ok := x.Outcome.(*ExecutionResult_CloneReady); ok {
			return x.CloneReady
		}
	}
	return nil
}

func (x *ExecutionResult) GetCloneFailed() *CloneFailed {
	if x != nil {
		if x, ok := x.Outcome.(*ExecutionResult_CloneFailed); ok {
			return x.CloneFailed
		}
	}
	return nil
}

type isExecutionResult_Outcome interface {
	isExecutionResult_Outcome()
}

type ExecutionResult_CloneReady struct {
	CloneReady *CloneReady `protobuf:"bytes,2,opt,name=clone_ready,json=cloneReady,proto3,oneof"`
}

type ExecutionResult_CloneFailed struct {
	CloneFailed *CloneFailed `protobuf:"bytes,3,opt,name=clone_failed,json=cloneFailed,proto3,oneof"`
}

func (*ExecutionResult_CloneReady) isExecutionResult_Outcome() {}

func (*ExecutionResult_CloneFailed) isExecutionResult_Outcome() {}

// Work Cloud accepted in its own business transaction and handed to Controllers.
type WorkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Input         *ExecutionInput        `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{8}
}

func (x *WorkItem) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *WorkItem) GetInput() *ExecutionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

// One registered execution and its durable state. No result means awaiting reconciliation, never
// failure.
type ExecutionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Input         *ExecutionInput        `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Result        *ExecutionResult       `protobuf:"bytes,5,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRecord) Reset() {
	*x = ExecutionRecord{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRecord) ProtoMessage() {}

func (x *ExecutionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRecord.ProtoReflect.Descriptor instead.
func (*ExecutionRecord) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutionRecord) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ExecutionRecord) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionRecord) GetInput() *ExecutionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecutionRecord) GetResult() *ExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ClaimWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimWorkRequest) Reset() {
	*x = ClaimWorkRequest{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWorkRequest) ProtoMessage() {}

func (x *ClaimWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWorkRequest.ProtoReflect.Descriptor instead.
func (*ClaimWorkRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimWorkRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *ClaimWorkRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type ClaimWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *WorkItem              `protobuf:"bytes,1,opt,name=item,proto3,oneof" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimWorkResponse) Reset() {
	*x = ClaimWorkResponse{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWorkResponse) ProtoMessage() {}

func (x *ClaimWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWorkResponse.ProtoReflect.Descriptor instead.
func (*ClaimWorkResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{11}
}

func (x *ClaimWorkResponse) GetItem() *WorkItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type RecordDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Input         *ExecutionInput        `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordDispatchRequest) Reset() {
	*x = RecordDispatchRequest{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDispatchRequest) ProtoMessage() {}

func (x *RecordDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDispatchRequest.ProtoReflect.Descriptor instead.
func (*RecordDispatchRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{12}
}

func (x *RecordDispatchRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *RecordDispatchRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RecordDispatchRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RecordDispatchRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RecordDispatchRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RecordDispatchRequest) GetInput() *ExecutionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type RecordDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExecutionRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordDispatchResponse) Reset() {
	*x = RecordDispatchResponse{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDispatchResponse) ProtoMessage() {}

func (x *RecordDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDispatchResponse.ProtoReflect.Descriptor instead.
func (*RecordDispatchResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{13}
}

func (x *RecordDispatchResponse) GetRecord() *ExecutionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type TakeOverNodeEventRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch        int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	OperationId  string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId  string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Event sequence assigned by the Node; the receipt (execution_id, sequence) is the only basis
	// for an acknowledgement.
	Sequence uint64           `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Result   *ExecutionResult `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	// Canonical encoding of the original Node event, kept verbatim so a replayed event with the
	// same sequence but different content is detected as a conflict.
	Event         []byte `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeOverNodeEventRequest) Reset() {
	*x = TakeOverNodeEventRequest{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOverNodeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverNodeEventRequest) ProtoMessage() {}

func (x *TakeOverNodeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverNodeEventRequest.ProtoReflect.Descriptor instead.
func (*TakeOverNodeEventRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{14}
}

func (x *TakeOverNodeEventRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *TakeOverNodeEventRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TakeOverNodeEventRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *TakeOverNodeEventRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TakeOverNodeEventRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TakeOverNodeEventRequest) GetResult() *ExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TakeOverNodeEventRequest) GetEvent() []byte {
	if x != nil {
		return x.Event
	}
	return nil
}

type TakeOverNodeEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExecutionRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeOverNodeEventResponse) Reset() {
	*x = TakeOverNodeEventResponse{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOverNodeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverNodeEventResponse) ProtoMessage() {}

func (x *TakeOverNodeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverNodeEventResponse.ProtoReflect.Descriptor instead.
func (*TakeOverNodeEventResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{15}
}

func (x *TakeOverNodeEventResponse) GetRecord() *ExecutionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type RecordQueriedResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Result        *ExecutionResult       `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordQueriedResultRequest) Reset() {
	*x = RecordQueriedResultRequest{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordQueriedResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordQueriedResultRequest) ProtoMessage() {}

func (x *RecordQueriedResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordQueriedResultRequest.ProtoReflect.Descriptor instead.
func (*RecordQueriedResultRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{16}
}

func (x *RecordQueriedResultRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *RecordQueriedResultRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RecordQueriedResultRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RecordQueriedResultRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RecordQueriedResultRequest) GetResult() *ExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type RecordQueriedResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExecutionRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordQueriedResultResponse) Reset() {
	*x = RecordQueriedResultResponse{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordQueriedResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordQueriedResultResponse) ProtoMessage() {}

func (x *RecordQueriedResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordQueriedResultResponse.ProtoReflect.Descriptor instead.
func (*RecordQueriedResultResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{17}
}

func (x *RecordQueriedResultResponse) GetRecord() *ExecutionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type GetDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDispatchRequest) Reset() {
	*x = GetDispatchRequest{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDispatchRequest) ProtoMessage() {}

func (x *GetDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDispatchRequest.ProtoReflect.Descriptor instead.
func (*GetDispatchRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{18}
}

func (x *GetDispatchRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ExecutionRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDispatchResponse) Reset() {
	*x = GetDispatchResponse{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDispatchResponse) ProtoMessage() {}

func (x *GetDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDispatchResponse.ProtoReflect.Descriptor instead.
func (*GetDispatchResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{19}
}

func (x *GetDispatchResponse) GetRecord() *ExecutionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListPendingDispatchesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Restricts to executions dispatched to one Node; empty lists every pending execution.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingDispatchesRequest) Reset() {
	*x = ListPendingDispatchesRequest{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingDispatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingDispatchesRequest) ProtoMessage() {}

func (x *ListPendingDispatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingDispatchesRequest.ProtoReflect.Descriptor instead.
func (*ListPendingDispatchesRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{20}
}

func (x *ListPendingDispatchesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ListPendingDispatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ExecutionRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingDispatchesResponse) Reset() {
	*x = ListPendingDispatchesResponse{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingDispatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingDispatchesResponse) ProtoMessage() {}

func (x *ListPendingDispatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingDispatchesResponse.ProtoReflect.Descriptor instead.
func (*ListPendingDispatchesResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{21}
}

func (x *ListPendingDispatchesResponse) GetRecords() []*ExecutionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// MintSkillRetrievalRequest asks Cloud to mint retrieval capabilities for one or more frozen skill
// revisions. The caller supplies only durable identities (execution_id, attempt_id,
// skill_revision_ids) — never a locator, bucket, key, or workspace ownership claim (ADR D9/D12/D17).
type MintSkillRetrievalRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AttemptId        string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	SkillRevisionIds []string               `protobuf:"bytes,3,rep,name=skill_revision_ids,json=skillRevisionIds,proto3" json:"skill_revision_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MintSkillRetrievalRequest) Reset() {
	*x = MintSkillRetrievalRequest{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSkillRetrievalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSkillRetrievalRequest) ProtoMessage() {}

func (x *MintSkillRetrievalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSkillRetrievalRequest.ProtoReflect.Descriptor instead.
func (*MintSkillRetrievalRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{22}
}

func (x *MintSkillRetrievalRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *MintSkillRetrievalRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *MintSkillRetrievalRequest) GetSkillRevisionIds() []string {
	if x != nil {
		return x.SkillRevisionIds
	}
	return nil
}

// SkillRetrievalCapability is one minted short-lived exact-object GET credential (ADR D3/D5). `url`
// is a bearer credential: transient delivery state, never persisted or logged. `method` is fixed to
// "GET".
type SkillRetrievalCapability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SkillRevisionId string                 `protobuf:"bytes,1,opt,name=skill_revision_id,json=skillRevisionId,proto3" json:"skill_revision_id,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url             string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// expires_at is the authoritative expiry taken from the actual signing validity (ADR D24).
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillRetrievalCapability) Reset() {
	*x = SkillRetrievalCapability{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRetrievalCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRetrievalCapability) ProtoMessage() {}

func (x *SkillRetrievalCapability) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRetrievalCapability.ProtoReflect.Descriptor instead.
func (*SkillRetrievalCapability) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{23}
}

func (x *SkillRetrievalCapability) GetSkillRevisionId() string {
	if x != nil {
		return x.SkillRevisionId
	}
	return ""
}

func (x *SkillRetrievalCapability) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SkillRetrievalCapability) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SkillRetrievalCapability) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type MintSkillRetrievalResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Capabilities  []*SkillRetrievalCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintSkillRetrievalResponse) Reset() {
	*x = MintSkillRetrievalResponse{}
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintSkillRetrievalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintSkillRetrievalResponse) ProtoMessage() {}

func (x *MintSkillRetrievalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_executions_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintSkillRetrievalResponse.ProtoReflect.Descriptor instead.
func (*MintSkillRetrievalResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_executions_proto_rawDescGZIP(), []int{24}
}

func (x *MintSkillRetrievalResponse) GetCapabilities() []*SkillRetrievalCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_ora_cloud_internal_v1_executions_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_executions_proto_rawDesc = "" +
	"\n" +
	"&ora/cloud/internal/v1/executions.proto\x12\x15ora.cloud.internal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\fNodeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x13node_incarnation_id\x18\x02 \x01(\tR\x11nodeIncarnationId\"C\n" +
	"\tCloneSpec\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"\xdf\x01\n" +
	"\x0eSkillBundleRef\x12*\n" +
	"\x11skill_revision_id\x18\x01 \x01(\tR\x0fskillRevisionId\x12%\n" +
	"\x0econtent_digest\x18\x02 \x01(\tR\rcontentDigest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12%\n" +
	"\x0epackage_format\x18\x04 \x01(\tR\rpackageFormat\x124\n" +
	"\x16package_format_version\x18\x05 \x01(\x05R\x14packageFormatVersion\"Z\n" +
	"\fSkillRunSpec\x12J\n" +
	"\rskill_bundles\x18\x01 \x03(\v2%.ora.cloud.internal.v1.SkillBundleRefR\fskillBundles\"\x96\x01\n" +
	"\x0eExecutionInput\x128\n" +
	"\x05clone\x18\x01 \x01(\v2 .ora.cloud.internal.v1.CloneSpecH\x00R\x05clone\x12B\n" +
	"\tskill_run\x18\x02 \x01(\v2#.ora.cloud.internal.v1.SkillRunSpecH\x00R\bskillRunB\x06\n" +
	"\x04spec\"8\n" +
	"\n" +
	"CloneReady\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\"\x8c\x01\n" +
	"\vCloneFailed\x12A\n" +
	"\x06reason\x18\x01 \x01(\x0e2).ora.cloud.internal.v1.CloneFailureReasonR\x06reason\x12(\n" +
	"\rretained_path\x18\x02 \x01(\tH\x00R\fretainedPath\x88\x01\x01B\x10\n" +
	"\x0e_retained_path\"\xe4\x01\n" +
	"\x0fExecutionResult\x127\n" +
	"\x04node\x18\x01 \x01(\v2#.ora.cloud.internal.v1.NodeIdentityR\x04node\x12D\n" +
	"\vclone_ready\x18\x02 \x01(\v2!.ora.cloud.internal.v1.CloneReadyH\x00R\n" +
	"cloneReady\x12G\n" +
	"\fclone_failed\x18\x03 \x01(\v2\".ora.cloud.internal.v1.CloneFailedH\x00R\vcloneFailedB\t\n" +
	"\aoutcome\"j\n" +
	"\bWorkItem\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12;\n" +
	"\x05input\x18\x02 \x01(\v2%.ora.cloud.internal.v1.ExecutionInputR\x05input\"\xfd\x01\n" +
	"\x0fExecutionRecord\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12;\n" +
	"\x05input\x18\x04 \x01(\v2%.ora.cloud.internal.v1.ExecutionInputR\x05input\x12C\n" +
	"\x06result\x18\x05 \x01(\v2&.ora.cloud.internal.v1.ExecutionResultH\x00R\x06result\x88\x01\x01B\t\n" +
	"\a_result\"M\n" +
	"\x10ClaimWorkRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\"V\n" +
	"\x11ClaimWorkResponse\x128\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.ora.cloud.internal.v1.WorkItemH\x00R\x04item\x88\x01\x01B\a\n" +
	"\x05_item\"\xee\x01\n" +
	"\x15RecordDispatchRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12;\n" +
	"\x05input\x18\x06 \x01(\v2%.ora.cloud.internal.v1.ExecutionInputR\x05input\"X\n" +
	"\x16RecordDispatchResponse\x12>\n" +
	"\x06record\x18\x01 \x01(\v2&.ora.cloud.internal.v1.ExecutionRecordR\x06record\"\x8d\x02\n" +
	"\x18TakeOverNodeEventRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x12>\n" +
	"\x06result\x18\x06 \x01(\v2&.ora.cloud.internal.v1.ExecutionResultR\x06result\x12\x14\n" +
	"\x05event\x18\a \x01(\fR\x05event\"[\n" +
	"\x19TakeOverNodeEventResponse\x12>\n" +
	"\x06record\x18\x01 \x01(\v2&.ora.cloud.internal.v1.ExecutionRecordR\x06record\"\xdd\x01\n" +
	"\x1aRecordQueriedResultRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12>\n" +
	"\x06result\x18\x05 \x01(\v2&.ora.cloud.internal.v1.ExecutionResultR\x06result\"]\n" +
	"\x1bRecordQueriedResultResponse\x12>\n" +
	"\x06record\x18\x01 \x01(\v2&.ora.cloud.internal.v1.ExecutionRecordR\x06record\"7\n" +
	"\x12GetDispatchRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"U\n" +
	"\x13GetDispatchResponse\x12>\n" +
	"\x06record\x18\x01 \x01(\v2&.ora.cloud.internal.v1.ExecutionRecordR\x06record\"7\n" +
	"\x1cListPendingDispatchesRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"a\n" +
	"\x1dListPendingDispatchesResponse\x12@\n" +
	"\arecords\x18\x01 \x03(\v2&.ora.cloud.internal.v1.ExecutionRecordR\arecords\"\x8b\x01\n" +
	"\x19MintSkillRetrievalRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12,\n" +
	"\x12skill_revision_ids\x18\x03 \x03(\tR\x10skillRevisionIds\"\xab\x01\n" +
	"\x18SkillRetrievalCapability\x12*\n" +
	"\x11skill_revision_id\x18\x01 \x01(\tR\x0fskillRevisionId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"q\n" +
	"\x1aMintSkillRetrievalResponse\x12S\n" +
	"\fcapabilities\x18\x01 \x03(\v2/.ora.cloud.internal.v1.SkillRetrievalCapabilityR\fcapabilities*\xec\x01\n" +
	"\x12CloneFailureReason\x12$\n" +
	" CLONE_FAILURE_REASON_UNSPECIFIED\x10\x00\x12+\n" +
	"'CLONE_FAILURE_REASON_SOURCE_UNAVAILABLE\x10\x01\x12)\n" +
	"%CLONE_FAILURE_REASON_BRANCH_NOT_FOUND\x10\x02\x12-\n" +
	")CLONE_FAILURE_REASON_DESTINATION_CONFLICT\x10\x03\x12)\n" +
	"%CLONE_FAILURE_REASON_OPERATION_FAILED\x10\x042\xbd\x06\n" +
	"\x10ExecutionService\x12^\n" +
	"\tClaimWork\x12'.ora.cloud.internal.v1.ClaimWorkRequest\x1a(.ora.cloud.internal.v1.ClaimWorkResponse\x12m\n" +
	"\x0eRecordDispatch\x12,.ora.cloud.internal.v1.RecordDispatchRequest\x1a-.ora.cloud.internal.v1.RecordDispatchResponse\x12v\n" +
	"\x11TakeOverNodeEvent\x12/.ora.cloud.internal.v1.TakeOverNodeEventRequest\x1a0.ora.cloud.internal.v1.TakeOverNodeEventResponse\x12|\n" +
	"\x13RecordQueriedResult\x121.ora.cloud.internal.v1.RecordQueriedResultRequest\x1a2.ora.cloud.internal.v1.RecordQueriedResultResponse\x12d\n" +
	"\vGetDispatch\x12).ora.cloud.internal.v1.GetDispatchRequest\x1a*.ora.cloud.internal.v1.GetDispatchResponse\x12\x82\x01\n" +
	"\x15ListPendingDispatches\x123.ora.cloud.internal.v1.ListPendingDispatchesRequest\x1a4.ora.cloud.internal.v1.ListPendingDispatchesResponse\x12y\n" +
	"\x12MintSkillRetrieval\x120.ora.cloud.internal.v1.MintSkillRetrievalRequest\x1a1.ora.cloud.internal.v1.MintSkillRetrievalResponseb\x06proto3"

var (
	file_ora_cloud_internal_v1_executions_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_executions_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_executions_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_executions_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_executions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_executions_proto_rawDesc), len(file_ora_cloud_internal_v1_executions_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_executions_proto_rawDescData
}

var file_ora_cloud_internal_v1_executions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ora_cloud_internal_v1_executions_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_ora_cloud_internal_v1_executions_proto_goTypes = []any{
	(CloneFailureReason)(0),               // 0: ora.cloud.internal.v1.CloneFailureReason
	(*NodeIdentity)(nil),                  // 1: ora.cloud.internal.v1.NodeIdentity
	(*CloneSpec)(nil),                     // 2: ora.cloud.internal.v1.CloneSpec
	(*SkillBundleRef)(nil),                // 3: ora.cloud.internal.v1.SkillBundleRef
	(*SkillRunSpec)(nil),                  // 4: ora.cloud.internal.v1.SkillRunSpec
	(*ExecutionInput)(nil),                // 5: ora.cloud.internal.v1.ExecutionInput
	(*CloneReady)(nil),                    // 6: ora.cloud.internal.v1.CloneReady
	(*CloneFailed)(nil),                   // 7: ora.cloud.internal.v1.CloneFailed
	(*ExecutionResult)(nil),               // 8: ora.cloud.internal.v1.ExecutionResult
	(*WorkItem)(nil),                      // 9: ora.cloud.internal.v1.WorkItem
	(*ExecutionRecord)(nil),               // 10: ora.cloud.internal.v1.ExecutionRecord
	(*ClaimWorkRequest)(nil),              // 11: ora.cloud.internal.v1.ClaimWorkRequest
	(*ClaimWorkResponse)(nil),             // 12: ora.cloud.internal.v1.ClaimWorkResponse
	(*RecordDispatchRequest)(nil),         // 13: ora.cloud.internal.v1.RecordDispatchRequest
	(*RecordDispatchResponse)(nil),        // 14: ora.cloud.internal.v1.RecordDispatchResponse
	(*TakeOverNodeEventRequest)(nil),      // 15: ora.cloud.internal.v1.TakeOverNodeEventRequest
	(*TakeOverNodeEventResponse)(nil),     // 16: ora.cloud.internal.v1.TakeOverNodeEventResponse
	(*RecordQueriedResultRequest)(nil),    // 17: ora.cloud.internal.v1.RecordQueriedResultRequest
	(*RecordQueriedResultResponse)(nil),   // 18: ora.cloud.internal.v1.RecordQueriedResultResponse
	(*GetDispatchRequest)(nil),            // 19: ora.cloud.internal.v1.GetDispatchRequest
	(*GetDispatchResponse)(nil),           // 20: ora.cloud.internal.v1.GetDispatchResponse
	(*ListPendingDispatchesRequest)(nil),  // 21: ora.cloud.internal.v1.ListPendingDispatchesRequest
	(*ListPendingDispatchesResponse)(nil), // 22: ora.cloud.internal.v1.ListPendingDispatchesResponse
	(*MintSkillRetrievalRequest)(nil),     // 23: ora.cloud.internal.v1.MintSkillRetrievalRequest
	(*SkillRetrievalCapability)(nil),      // 24: ora.cloud.internal.v1.SkillRetrievalCapability
	(*MintSkillRetrievalResponse)(nil),    // 25: ora.cloud.internal.v1.MintSkillRetrievalResponse
	(*timestamppb.Timestamp)(nil),         // 26: google.protobuf.Timestamp
}
var file_ora_cloud_internal_v1_executions_proto_depIdxs = []int32{
	3,  // 0: ora.cloud.internal.v1.SkillRunSpec.skill_bundles:type_name -> ora.cloud.internal.v1.SkillBundleRef
	2,  // 1: ora.cloud.internal.v1.ExecutionInput.clone:type_name -> ora.cloud.internal.v1.CloneSpec
	4,  // 2: ora.cloud.internal.v1.ExecutionInput.skill_run:type_name -> ora.cloud.internal.v1.SkillRunSpec
	0,  // 3: ora.cloud.internal.v1.CloneFailed.reason:type_name -> ora.cloud.internal.v1.CloneFailureReason
	1,  // 4: ora.cloud.internal.v1.ExecutionResult.node:type_name -> ora.cloud.internal.v1.NodeIdentity
	6,  // 5: ora.cloud.internal.v1.ExecutionResult.clone_ready:type_name -> ora.cloud.internal.v1.CloneReady
	7,  // 6: ora.cloud.internal.v1.ExecutionResult.clone_failed:type_name -> ora.cloud.internal.v1.CloneFailed
	5,  // 7: ora.cloud.internal.v1.WorkItem.input:type_name -> ora.cloud.internal.v1.ExecutionInput
	5,  // 8: ora.cloud.internal.v1.ExecutionRecord.input:type_name -> ora.cloud.internal.v1.ExecutionInput
	8,  // 9: ora.cloud.internal.v1.ExecutionRecord.result:type_name -> ora.cloud.internal.v1.ExecutionResult
	9,  // 10: ora.cloud.internal.v1.ClaimWorkResponse.item:type_name -> ora.cloud.internal.v1.WorkItem
	5,  // 11: ora.cloud.internal.v1.RecordDispatchRequest.input:type_name -> ora.cloud.internal.v1.ExecutionInput
	10, // 12: ora.cloud.internal.v1.RecordDispatchResponse.record:type_name -> ora.cloud.internal.v1.ExecutionRecord
	8,  // 13: ora.cloud.internal.v1.TakeOverNodeEventRequest.result:type_name -> ora.cloud.internal.v1.ExecutionResult
	10, // 14: ora.cloud.internal.v1.TakeOverNodeEventResponse.record:type_name -> ora.cloud.internal.v1.ExecutionRecord
	8,  // 15: ora.cloud.internal.v1.RecordQueriedResultRequest.result:type_name -> ora.cloud.internal.v1.ExecutionResult
	10, // 16: ora.cloud.internal.v1.RecordQueriedResultResponse.record:type_name -> ora.cloud.internal.v1.ExecutionRecord
	10, // 17: ora.cloud.internal.v1.GetDispatchResponse.record:type_name -> ora.cloud.internal.v1.ExecutionRecord
	10, // 18: ora.cloud.internal.v1.ListPendingDispatchesResponse.records:type_name -> ora.cloud.internal.v1.ExecutionRecord
	26, // 19: ora.cloud.internal.v1.SkillRetrievalCapability.expires_at:type_name -> google.protobuf.Timestamp
	24, // 20: ora.cloud.internal.v1.MintSkillRetrievalResponse.capabilities:type_name -> ora.cloud.internal.v1.SkillRetrievalCapability
	11, // 21: ora.cloud.internal.v1.ExecutionService.ClaimWork:input_type -> ora.cloud.internal.v1.ClaimWorkRequest
	13, // 22: ora.cloud.internal.v1.ExecutionService.RecordDispatch:input_type -> ora.cloud.internal.v1.RecordDispatchRequest
	15, // 23: ora.cloud.internal.v1.ExecutionService.TakeOverNodeEvent:input_type -> ora.cloud.internal.v1.TakeOverNodeEventRequest
	17, // 24: ora.cloud.internal.v1.ExecutionService.RecordQueriedResult:input_type -> ora.cloud.internal.v1.RecordQueriedResultRequest
	19, // 25: ora.cloud.internal.v1.ExecutionService.GetDispatch:input_type -> ora.cloud.internal.v1.GetDispatchRequest
	21, // 26: ora.cloud.internal.v1.ExecutionService.ListPendingDispatches:input_type -> ora.cloud.internal.v1.ListPendingDispatchesRequest
	23, // 27: ora.cloud.internal.v1.ExecutionService.MintSkillRetrieval:input_type -> ora.cloud.internal.v1.MintSkillRetrievalRequest
	12, // 28: ora.cloud.internal.v1.ExecutionService.ClaimWork:output_type -> ora.cloud.internal.v1.ClaimWorkResponse
	14, // 29: ora.cloud.internal.v1.ExecutionService.RecordDispatch:output_type -> ora.cloud.internal.v1.RecordDispatchResponse
	16, // 30: ora.cloud.internal.v1.ExecutionService.TakeOverNodeEvent:output_type -> ora.cloud.internal.v1.TakeOverNodeEventResponse
	18, // 31: ora.cloud.internal.v1.ExecutionService.RecordQueriedResult:output_type -> ora.cloud.internal.v1.RecordQueriedResultResponse
	20, // 32: ora.cloud.internal.v1.ExecutionService.GetDispatch:output_type -> ora.cloud.internal.v1.GetDispatchResponse
	22, // 33: ora.cloud.internal.v1.ExecutionService.ListPendingDispatches:output_type -> ora.cloud.internal.v1.ListPendingDispatchesResponse
	25, // 34: ora.cloud.internal.v1.ExecutionService.MintSkillRetrieval:output_type -> ora.cloud.internal.v1.MintSkillRetrievalResponse
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_executions_proto_init() }
func file_ora_cloud_internal_v1_executions_proto_init() {
	if File_ora_cloud_internal_v1_executions_proto != nil {
		return
	}
	file_ora_cloud_internal_v1_executions_proto_msgTypes[4].OneofWrappers = []any{
		(*ExecutionInput_Clone)(nil),
		(*ExecutionInput_SkillRun)(nil),
	}
	file_ora_cloud_internal_v1_executions_proto_msgTypes[6].OneofWrappers = []any{}
	file_ora_cloud_internal_v1_executions_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecutionResult_CloneReady)(nil),
		(*ExecutionResult_CloneFailed)(nil),
	}
	file_ora_cloud_internal_v1_executions_proto_msgTypes[9].OneofWrappers = []any{}
	file_ora_cloud_internal_v1_executions_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_executions_proto_rawDesc), len(file_ora_cloud_internal_v1_executions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ora_cloud_internal_v1_executions_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_executions_proto_depIdxs,
		EnumInfos:         file_ora_cloud_internal_v1_executions_proto_enumTypes,
		MessageInfos:      file_ora_cloud_internal_v1_executions_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_executions_proto = out.File
	file_ora_cloud_internal_v1_executions_proto_goTypes = nil
	file_ora_cloud_internal_v1_executions_proto_depIdxs = nil
}
