// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/lease.proto

package controlpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lease struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ControllerId of the current holder, as the caller named itself in x-ora-controller-id metadata.
	HolderId string `protobuf:"bytes,1,opt,name=holder_id,json=holderId,proto3" json:"holder_id,omitempty"`
	// Monotonic fencing token; increases every time the lease changes hands.
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_lease_proto_rawDescGZIP(), []int{0}
}

func (x *Lease) GetHolderId() string {
	if x != nil {
		return x.HolderId
	}
	return ""
}

func (x *Lease) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Lease) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type AcquireLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLeaseRequest) Reset() {
	*x = AcquireLeaseRequest{}
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLeaseRequest) ProtoMessage() {}

func (x *AcquireLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLeaseRequest.ProtoReflect.Descriptor instead.
func (*AcquireLeaseRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_lease_proto_rawDescGZIP(), []int{1}
}

type AcquireLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLeaseResponse) Reset() {
	*x = AcquireLeaseResponse{}
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLeaseResponse) ProtoMessage() {}

func (x *AcquireLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLeaseResponse.ProtoReflect.Descriptor instead.
func (*AcquireLeaseResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_lease_proto_rawDescGZIP(), []int{2}
}

func (x *AcquireLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RenewLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_lease_proto_rawDescGZIP(), []int{3}
}

func (x *RenewLeaseRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type RenewLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_lease_proto_rawDescGZIP(), []int{4}
}

func (x *RenewLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type ReleaseLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLeaseRequest) Reset() {
	*x = ReleaseLeaseRequest{}
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLeaseRequest) ProtoMessage() {}

func (x *ReleaseLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLeaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLeaseRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_lease_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseLeaseRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type ReleaseLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLeaseResponse) Reset() {
	*x = ReleaseLeaseResponse{}
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLeaseResponse) ProtoMessage() {}

func (x *ReleaseLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_lease_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLeaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLeaseResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_lease_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseLeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

var File_ora_cloud_internal_v1_lease_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_lease_proto_rawDesc = "" +
	"\n" +
	"!ora/cloud/internal/v1/lease.proto\x12\x15ora.cloud.internal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\x05Lease\x12\x1b\n" +
	"\tholder_id\x18\x01 \x01(\tR\bholderId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x15\n" +
	"\x13AcquireLeaseRequest\"J\n" +
	"\x14AcquireLeaseResponse\x122\n" +
	"\x05lease\x18\x01 \x01(\v2\x1c.ora.cloud.internal.v1.LeaseR\x05lease\")\n" +
	"\x11RenewLeaseRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"H\n" +
	"\x12RenewLeaseResponse\x122\n" +
	"\x05lease\x18\x01 \x01(\v2\x1c.ora.cloud.internal.v1.LeaseR\x05lease\"+\n" +
	"\x13ReleaseLeaseRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"J\n" +
	"\x14ReleaseLeaseResponse\x122\n" +
	"\x05lease\x18\x01 \x01(\v2\x1c.ora.cloud.internal.v1.LeaseR\x05lease2\xcd\x02\n" +
	"\x16ControllerLeaseService\x12g\n" +
	"\fAcquireLease\x12*.ora.cloud.internal.v1.AcquireLeaseRequest\x1a+.ora.cloud.internal.v1.AcquireLeaseResponse\x12a\n" +
	"\n" +
	"RenewLease\x12(.ora.cloud.internal.v1.RenewLeaseRequest\x1a).ora.cloud.internal.v1.RenewLeaseResponse\x12g\n" +
	"\fReleaseLease\x12*.ora.cloud.internal.v1.ReleaseLeaseRequest\x1a+.ora.cloud.internal.v1.ReleaseLeaseResponseB\xdb\x01\n" +
	"\x19com.ora.cloud.internal.v1B\n" +
	"LeaseProtoP\x01Z;github.com/wanglongan587/cloud/internal/controlpb;controlpb\xa2\x02\x03OCI\xaa\x02\x15Ora.Cloud.Internal.V1\xca\x02\x15Ora\\Cloud\\Internal\\V1\xe2\x02!Ora\\Cloud\\Internal\\V1\\GPBMetadata\xea\x02\x18Ora::Cloud::Internal::V1b\x06proto3"

var (
	file_ora_cloud_internal_v1_lease_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_lease_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_lease_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_lease_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_lease_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_lease_proto_rawDesc), len(file_ora_cloud_internal_v1_lease_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_lease_proto_rawDescData
}

var file_ora_cloud_internal_v1_lease_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ora_cloud_internal_v1_lease_proto_goTypes = []any{
	(*Lease)(nil),                 // 0: ora.cloud.internal.v1.Lease
	(*AcquireLeaseRequest)(nil),   // 1: ora.cloud.internal.v1.AcquireLeaseRequest
	(*AcquireLeaseResponse)(nil),  // 2: ora.cloud.internal.v1.AcquireLeaseResponse
	(*RenewLeaseRequest)(nil),     // 3: ora.cloud.internal.v1.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),    // 4: ora.cloud.internal.v1.RenewLeaseResponse
	(*ReleaseLeaseRequest)(nil),   // 5: ora.cloud.internal.v1.ReleaseLeaseRequest
	(*ReleaseLeaseResponse)(nil),  // 6: ora.cloud.internal.v1.ReleaseLeaseResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_ora_cloud_internal_v1_lease_proto_depIdxs = []int32{
	7, // 0: ora.cloud.internal.v1.Lease.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: ora.cloud.internal.v1.AcquireLeaseResponse.lease:type_name -> ora.cloud.internal.v1.Lease
	0, // 2: ora.cloud.internal.v1.RenewLeaseResponse.lease:type_name -> ora.cloud.internal.v1.Lease
	0, // 3: ora.cloud.internal.v1.ReleaseLeaseResponse.lease:type_name -> ora.cloud.internal.v1.Lease
	1, // 4: ora.cloud.internal.v1.ControllerLeaseService.AcquireLease:input_type -> ora.cloud.internal.v1.AcquireLeaseRequest
	3, // 5: ora.cloud.internal.v1.ControllerLeaseService.RenewLease:input_type -> ora.cloud.internal.v1.RenewLeaseRequest
	5, // 6: ora.cloud.internal.v1.ControllerLeaseService.ReleaseLease:input_type -> ora.cloud.internal.v1.ReleaseLeaseRequest
	2, // 7: ora.cloud.internal.v1.ControllerLeaseService.AcquireLease:output_type -> ora.cloud.internal.v1.AcquireLeaseResponse
	4, // 8: ora.cloud.internal.v1.ControllerLeaseService.RenewLease:output_type -> ora.cloud.internal.v1.RenewLeaseResponse
	6, // 9: ora.cloud.internal.v1.ControllerLeaseService.ReleaseLease:output_type -> ora.cloud.internal.v1.ReleaseLeaseResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_lease_proto_init() }
func file_ora_cloud_internal_v1_lease_proto_init() {
	if File_ora_cloud_internal_v1_lease_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_lease_proto_rawDesc), len(file_ora_cloud_internal_v1_lease_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ora_cloud_internal_v1_lease_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_lease_proto_depIdxs,
		MessageInfos:      file_ora_cloud_internal_v1_lease_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_lease_proto = out.File
	file_ora_cloud_internal_v1_lease_proto_goTypes = nil
	file_ora_cloud_internal_v1_lease_proto_depIdxs = nil
}
