// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ora/cloud/internal/v1/lease.proto

package controlpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerLeaseService_AcquireLease_FullMethodName = "/ora.cloud.internal.v1.ControllerLeaseService/AcquireLease"
	ControllerLeaseService_RenewLease_FullMethodName   = "/ora.cloud.internal.v1.ControllerLeaseService/RenewLease"
	ControllerLeaseService_ReleaseLease_FullMethodName = "/ora.cloud.internal.v1.ControllerLeaseService/ReleaseLease"
)

// ControllerLeaseServiceClient is the client API for ControllerLeaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The single global coordination lease. Every state-changing call carries the holder's `epoch`;
// Cloud rejects writes whose epoch is not the current valid lease so a stale Controller cannot
// overwrite newer state. Expiry is measured on the database clock, never the caller's.
type ControllerLeaseServiceClient interface {
	// Takes the lease when it is free or expired, or confirms it when the caller already holds it.
	// A valid lease held by someone else fails with FAILED_PRECONDITION (LEASE_HELD).
	AcquireLease(ctx context.Context, in *AcquireLeaseRequest, opts ...grpc.CallOption) (*AcquireLeaseResponse, error)
	// Extends the caller's valid lease; a stale epoch fails with FAILED_PRECONDITION (STALE_CONTROLLER).
	RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error)
	// Ends the caller's valid lease immediately so another worker can acquire it.
	ReleaseLease(ctx context.Context, in *ReleaseLeaseRequest, opts ...grpc.CallOption) (*ReleaseLeaseResponse, error)
}

type controllerLeaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerLeaseServiceClient(cc grpc.ClientConnInterface) ControllerLeaseServiceClient {
	return &controllerLeaseServiceClient{cc}
}

func (c *controllerLeaseServiceClient) AcquireLease(ctx context.Context, in *AcquireLeaseRequest, opts ...grpc.CallOption) (*AcquireLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLeaseResponse)
	err := c.cc.Invoke(ctx, ControllerLeaseService_AcquireLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerLeaseServiceClient) RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewLeaseResponse)
	err := c.cc.Invoke(ctx, ControllerLeaseService_RenewLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerLeaseServiceClient) ReleaseLease(ctx context.Context, in *ReleaseLeaseRequest, opts ...grpc.CallOption) (*ReleaseLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseLeaseResponse)
	err := c.cc.Invoke(ctx, ControllerLeaseService_ReleaseLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerLeaseServiceServer is the server API for ControllerLeaseService service.
// All implementations must embed UnimplementedControllerLeaseServiceServer
// for forward compatibility.
//
// The single global coordination lease. Every state-changing call carries the holder's `epoch`;
// Cloud rejects writes whose epoch is not the current valid lease so a stale Controller cannot
// overwrite newer state. Expiry is measured on the database clock, never the caller's.
type ControllerLeaseServiceServer interface {
	// Takes the lease when it is free or expired, or confirms it when the caller already holds it.
	// A valid lease held by someone else fails with FAILED_PRECONDITION (LEASE_HELD).
	AcquireLease(context.Context, *AcquireLeaseRequest) (*AcquireLeaseResponse, error)
	// Extends the caller's valid lease; a stale epoch fails with FAILED_PRECONDITION (STALE_CONTROLLER).
	RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error)
	// Ends the caller's valid lease immediately so another worker can acquire it.
	ReleaseLease(context.Context, *ReleaseLeaseRequest) (*ReleaseLeaseResponse, error)
	mustEmbedUnimplementedControllerLeaseServiceServer()
}

// UnimplementedControllerLeaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerLeaseServiceServer struct{}

func (UnimplementedControllerLeaseServiceServer) AcquireLease(context.Context, *AcquireLeaseRequest) (*AcquireLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireLease not implemented")
}
func (UnimplementedControllerLeaseServiceServer) RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewLease not implemented")
}
func (UnimplementedControllerLeaseServiceServer) ReleaseLease(context.Context, *ReleaseLeaseRequest) (*ReleaseLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLease not implemented")
}
func (UnimplementedControllerLeaseServiceServer) mustEmbedUnimplementedControllerLeaseServiceServer() {
}
func (UnimplementedControllerLeaseServiceServer) testEmbeddedByValue() {}

// UnsafeControllerLeaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerLeaseServiceServer will
// result in compilation errors.
type UnsafeControllerLeaseServiceServer interface {
	mustEmbedUnimplementedControllerLeaseServiceServer()
}

func RegisterControllerLeaseServiceServer(s grpc.ServiceRegistrar, srv ControllerLeaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedControllerLeaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerLeaseService_ServiceDesc, srv)
}

func _ControllerLeaseService_AcquireLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerLeaseServiceServer).AcquireLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerLeaseService_AcquireLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerLeaseServiceServer).AcquireLease(ctx, req.(*AcquireLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerLeaseService_RenewLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerLeaseServiceServer).RenewLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerLeaseService_RenewLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerLeaseServiceServer).RenewLease(ctx, req.(*RenewLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerLeaseService_ReleaseLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerLeaseServiceServer).ReleaseLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerLeaseService_ReleaseLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerLeaseServiceServer).ReleaseLease(ctx, req.(*ReleaseLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerLeaseService_ServiceDesc is the grpc.ServiceDesc for ControllerLeaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerLeaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ora.cloud.internal.v1.ControllerLeaseService",
	HandlerType: (*ControllerLeaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireLease",
			Handler:    _ControllerLeaseService_AcquireLease_Handler,
		},
		{
			MethodName: "RenewLease",
			Handler:    _ControllerLeaseService_RenewLease_Handler,
		},
		{
			MethodName: "ReleaseLease",
			Handler:    _ControllerLeaseService_ReleaseLease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ora/cloud/internal/v1/lease.proto",
}
