// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ora/cloud/internal/v1/signals.proto

package controlpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlSignalService_Watch_FullMethodName = "/ora.cloud.internal.v1.ControlSignalService/Watch"
)

// ControlSignalServiceClient is the client API for ControlSignalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Cloud-to-Controller notifications over a stream the Controller opens. Signals are at-most-once
// accelerators: Cloud neither persists nor replays them, and none of them changes ownership or
// state. A Controller that loses the stream falls back to periodic ClaimWork and reopens it.
type ControlSignalServiceClient interface {
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type controlSignalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlSignalServiceClient(cc grpc.ClientConnInterface) ControlSignalServiceClient {
	return &controlSignalServiceClient{cc}
}

func (c *controlSignalServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlSignalService_ServiceDesc.Streams[0], ControlSignalService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlSignalService_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// ControlSignalServiceServer is the server API for ControlSignalService service.
// All implementations must embed UnimplementedControlSignalServiceServer
// for forward compatibility.
//
// Cloud-to-Controller notifications over a stream the Controller opens. Signals are at-most-once
// accelerators: Cloud neither persists nor replays them, and none of them changes ownership or
// state. A Controller that loses the stream falls back to periodic ClaimWork and reopens it.
type ControlSignalServiceServer interface {
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedControlSignalServiceServer()
}

// UnimplementedControlSignalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlSignalServiceServer struct{}

func (UnimplementedControlSignalServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedControlSignalServiceServer) mustEmbedUnimplementedControlSignalServiceServer() {}
func (UnimplementedControlSignalServiceServer) testEmbeddedByValue()                              {}

// UnsafeControlSignalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlSignalServiceServer will
// result in compilation errors.
type UnsafeControlSignalServiceServer interface {
	mustEmbedUnimplementedControlSignalServiceServer()
}

func RegisterControlSignalServiceServer(s grpc.ServiceRegistrar, srv ControlSignalServiceServer) {
	// If the following call pancis, it indicates UnimplementedControlSignalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlSignalService_ServiceDesc, srv)
}

func _ControlSignalService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlSignalServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlSignalService_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// ControlSignalService_ServiceDesc is the grpc.ServiceDesc for ControlSignalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlSignalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ora.cloud.internal.v1.ControlSignalService",
	HandlerType: (*ControlSignalServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ControlSignalService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ora/cloud/internal/v1/signals.proto",
}
