/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV1TenantsTidSpacesSidBody,
  DeleteApiV1TenantsTidSpacesSidMembersUidBody,
  Error,
  GetApiV1TenantsTidSpaces200,
  GetApiV1TenantsTidSpacesParams,
  GetApiV1TenantsTidSpacesSidMembers200,
  GetApiV1TenantsTidSpacesSidMembersParams,
  GetApiV1TenantsTidSpacesSidProjects200,
  GetApiV1TenantsTidSpacesSidProjectsParams,
  PatchApiV1TenantsTidSpacesSidBody,
  PostApiV1TenantsTidSpacesBody,
  PostApiV1TenantsTidSpacesSidMembersBody,
  PostApiV1TenantsTidSpacesSidProjects202,
  PostApiV1TenantsTidSpacesSidProjectsBody,
  PutApiV1TenantsTidSpacesSidMembersUidBody,
  Space,
  SpaceEvent,
  SpaceMember
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces
 */
export const getApiV1TenantsTidSpaces = (
    tid: string,
    params?: GetApiV1TenantsTidSpacesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidSpaces200>(
      {url: `/api/v1/tenants/${tid}/spaces`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesQueryKey = (tid: string,
    params?: GetApiV1TenantsTidSpacesParams,) => {
    return [
    `/api/v1/tenants/${tid}/spaces`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(tid: string,
    params?: GetApiV1TenantsTidSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesQueryKey(tid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>> = ({ signal }) => getApiV1TenantsTidSpaces(tid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>>
export type GetApiV1TenantsTidSpacesQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(
 tid: string,
    params: undefined |  GetApiV1TenantsTidSpacesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces
 */

export function useGetApiV1TenantsTidSpaces<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesQueryOptions(tid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Creates the collaboration space and its first owner atomically. slug is lowercase, immutable and unique per tenant. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/spaces
 */
export const postApiV1TenantsTidSpaces = (
    tid: string,
    postApiV1TenantsTidSpacesBody: PostApiV1TenantsTidSpacesBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Space>(
      {url: `/api/v1/tenants/${tid}/spaces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidSpacesBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidSpacesMutationKey = () => ['postApiV1TenantsTidSpaces'] as const;

export const getPostApiV1TenantsTidSpacesMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpaces>>, TError,PostApiV1TenantsTidSpacesMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpaces>>, TError,PostApiV1TenantsTidSpacesMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidSpacesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidSpaces>>, PostApiV1TenantsTidSpacesMutationVariables> = (props) => {
          const {tid,data} = props ?? {};

          return  postApiV1TenantsTidSpaces(tid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidSpacesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidSpaces>>>
    export type PostApiV1TenantsTidSpacesMutationBody = PostApiV1TenantsTidSpacesBody
    export type PostApiV1TenantsTidSpacesMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidSpacesMutationVariables = {tid: string;data: PostApiV1TenantsTidSpacesBody}

    /**
 * @summary POST /api/v1/tenants/:tid/spaces
 */
export const usePostApiV1TenantsTidSpaces = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpaces>>, TError,PostApiV1TenantsTidSpacesMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidSpaces>>,
        TError,
        PostApiV1TenantsTidSpacesMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidSpacesMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Archives the space (soft delete); requires owner and a matching version. Projects are unaffected. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary DELETE /api/v1/tenants/:tid/spaces/:sid
 */
export const deleteApiV1TenantsTidSpacesSid = (
    tid: string,
    sid: string,
    deleteApiV1TenantsTidSpacesSidBody: DeleteApiV1TenantsTidSpacesSidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Space>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1TenantsTidSpacesSidBody, signal
    },
      options);
    }




export const getDeleteApiV1TenantsTidSpacesSidMutationKey = () => ['deleteApiV1TenantsTidSpacesSid'] as const;

export const getDeleteApiV1TenantsTidSpacesSidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSid>>, TError,DeleteApiV1TenantsTidSpacesSidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSid>>, TError,DeleteApiV1TenantsTidSpacesSidMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1TenantsTidSpacesSidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSid>>, DeleteApiV1TenantsTidSpacesSidMutationVariables> = (props) => {
          const {tid,sid,data} = props ?? {};

          return  deleteApiV1TenantsTidSpacesSid(tid,sid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1TenantsTidSpacesSidMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSid>>>
    export type DeleteApiV1TenantsTidSpacesSidMutationBody = DeleteApiV1TenantsTidSpacesSidBody
    export type DeleteApiV1TenantsTidSpacesSidMutationError = ErrorType<Error>
    export type DeleteApiV1TenantsTidSpacesSidMutationVariables = {tid: string;sid: string;data: DeleteApiV1TenantsTidSpacesSidBody}

    /**
 * @summary DELETE /api/v1/tenants/:tid/spaces/:sid
 */
export const useDeleteApiV1TenantsTidSpacesSid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSid>>, TError,DeleteApiV1TenantsTidSpacesSidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSid>>,
        TError,
        DeleteApiV1TenantsTidSpacesSidMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1TenantsTidSpacesSidMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:sid
 */
export const getApiV1TenantsTidSpacesSid = (
    tid: string,
    sid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Space>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSidQueryKey = (tid: string,
    sid: string,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${sid}`
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSidQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError = ErrorType<Error>>(tid: string,
    sid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSidQueryKey(tid,sid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>> = ({ signal }) => getApiV1TenantsTidSpacesSid(tid,sid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && sid !== null && sid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>>
export type GetApiV1TenantsTidSpacesSidQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:sid
 */

export function useGetApiV1TenantsTidSpacesSid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSidQueryOptions(tid,sid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only name and description may change; slug is immutable. Requires admin or owner and a matching version. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PATCH /api/v1/tenants/:tid/spaces/:sid
 */
export const patchApiV1TenantsTidSpacesSid = (
    tid: string,
    sid: string,
    patchApiV1TenantsTidSpacesSidBody: PatchApiV1TenantsTidSpacesSidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Space>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchApiV1TenantsTidSpacesSidBody, signal
    },
      options);
    }




export const getPatchApiV1TenantsTidSpacesSidMutationKey = () => ['patchApiV1TenantsTidSpacesSid'] as const;

export const getPatchApiV1TenantsTidSpacesSidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSid>>, TError,PatchApiV1TenantsTidSpacesSidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSid>>, TError,PatchApiV1TenantsTidSpacesSidMutationVariables, TContext> => {

const mutationKey = getPatchApiV1TenantsTidSpacesSidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSid>>, PatchApiV1TenantsTidSpacesSidMutationVariables> = (props) => {
          const {tid,sid,data} = props ?? {};

          return  patchApiV1TenantsTidSpacesSid(tid,sid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1TenantsTidSpacesSidMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSid>>>
    export type PatchApiV1TenantsTidSpacesSidMutationBody = PatchApiV1TenantsTidSpacesSidBody
    export type PatchApiV1TenantsTidSpacesSidMutationError = ErrorType<Error>
    export type PatchApiV1TenantsTidSpacesSidMutationVariables = {tid: string;sid: string;data: PatchApiV1TenantsTidSpacesSidBody}

    /**
 * @summary PATCH /api/v1/tenants/:tid/spaces/:sid
 */
export const usePatchApiV1TenantsTidSpacesSid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSid>>, TError,PatchApiV1TenantsTidSpacesSidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSid>>,
        TError,
        PatchApiV1TenantsTidSpacesSidMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiV1TenantsTidSpacesSidMutationOptions(options), queryClient);
    }
    /**
 * Membership is verified before the stream opens. Events are lightweight invalidation notices published after commit; clients refetch authoritative state over REST.
 * @summary Stream workspace events over server-sent events
 */
export const getSpaceEvents = (
    tid: string,
    sid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SpaceEvent>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}/events`, method: 'GET', signal
    },
      options);
    }




export const getGetSpaceEventsQueryKey = (tid: string,
    sid: string,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${sid}/events`
    ] as const;
    }


export const getGetSpaceEventsQueryOptions = <TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(tid: string,
    sid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSpaceEventsQueryKey(tid,sid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSpaceEvents>>> = ({ signal }) => getSpaceEvents(tid,sid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && sid !== null && sid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSpaceEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getSpaceEvents>>>
export type GetSpaceEventsQueryError = ErrorType<Error>


export function useGetSpaceEvents<TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpaceEvents>>,
          TError,
          Awaited<ReturnType<typeof getSpaceEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpaceEvents<TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpaceEvents>>,
          TError,
          Awaited<ReturnType<typeof getSpaceEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpaceEvents<TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Stream workspace events over server-sent events
 */

export function useGetSpaceEvents<TData = Awaited<ReturnType<typeof getSpaceEvents>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpaceEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSpaceEventsQueryOptions(tid,sid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Lists the space's members; any active member of the space can read the member list. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:sid/members
 */
export const getApiV1TenantsTidSpacesSidMembers = (
    tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidMembersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidSpacesSidMembers200>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}/members`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSidMembersQueryKey = (tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidMembersParams,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${sid}/members`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSidMembersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError = ErrorType<Error>>(tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSidMembersQueryKey(tid,sid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>> = ({ signal }) => getApiV1TenantsTidSpacesSidMembers(tid,sid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && sid !== null && sid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSidMembersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>>
export type GetApiV1TenantsTidSpacesSidMembersQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSidMembers<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string,
    params: undefined |  GetApiV1TenantsTidSpacesSidMembersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSidMembers<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSidMembers<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:sid/members
 */

export function useGetApiV1TenantsTidSpacesSidMembers<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSidMembersQueryOptions(tid,sid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Adds an already-registered user to the space as a plain member by email, resolved in the caller's identity source. Admin or owner only. The target is atomically ensured tenant membership (existing role kept) and thereby gains access to the Projects and Runtime Workspaces shared in that workspace. Unknown or inactive email is 404 user_not_registered; adding an existing member returns the current membership unchanged. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/spaces/:sid/members
 */
export const postApiV1TenantsTidSpacesSidMembers = (
    tid: string,
    sid: string,
    postApiV1TenantsTidSpacesSidMembersBody: PostApiV1TenantsTidSpacesSidMembersBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SpaceMember>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidSpacesSidMembersBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidSpacesSidMembersMutationKey = () => ['postApiV1TenantsTidSpacesSidMembers'] as const;

export const getPostApiV1TenantsTidSpacesSidMembersMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidMembers>>, TError,PostApiV1TenantsTidSpacesSidMembersMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidMembers>>, TError,PostApiV1TenantsTidSpacesSidMembersMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidSpacesSidMembersMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidMembers>>, PostApiV1TenantsTidSpacesSidMembersMutationVariables> = (props) => {
          const {tid,sid,data} = props ?? {};

          return  postApiV1TenantsTidSpacesSidMembers(tid,sid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidSpacesSidMembersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidMembers>>>
    export type PostApiV1TenantsTidSpacesSidMembersMutationBody = PostApiV1TenantsTidSpacesSidMembersBody
    export type PostApiV1TenantsTidSpacesSidMembersMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidSpacesSidMembersMutationVariables = {tid: string;sid: string;data: PostApiV1TenantsTidSpacesSidMembersBody}

    /**
 * @summary POST /api/v1/tenants/:tid/spaces/:sid/members
 */
export const usePostApiV1TenantsTidSpacesSidMembers = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidMembers>>, TError,PostApiV1TenantsTidSpacesSidMembersMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidMembers>>,
        TError,
        PostApiV1TenantsTidSpacesSidMembersMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidSpacesSidMembersMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Removes a member's workspace membership (hard delete); owner only, admins and members cannot remove anyone. The user account, tenant membership and their resources are untouched and remain in the workspace; the removed member's access to the workspace, its projects and runtime workspaces is revoked. The last owner cannot be removed (409 space_last_owner). Requires a matching version and an idempotency key. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary DELETE /api/v1/tenants/:tid/spaces/:sid/members/:uid
 */
export const deleteApiV1TenantsTidSpacesSidMembersUid = (
    tid: string,
    sid: string,
    uid: string,
    deleteApiV1TenantsTidSpacesSidMembersUidBody: DeleteApiV1TenantsTidSpacesSidMembersUidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SpaceMember>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}/members/${uid}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1TenantsTidSpacesSidMembersUidBody, signal
    },
      options);
    }




export const getDeleteApiV1TenantsTidSpacesSidMembersUidMutationKey = () => ['deleteApiV1TenantsTidSpacesSidMembersUid'] as const;

export const getDeleteApiV1TenantsTidSpacesSidMembersUidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSidMembersUid>>, TError,DeleteApiV1TenantsTidSpacesSidMembersUidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSidMembersUid>>, TError,DeleteApiV1TenantsTidSpacesSidMembersUidMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1TenantsTidSpacesSidMembersUidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSidMembersUid>>, DeleteApiV1TenantsTidSpacesSidMembersUidMutationVariables> = (props) => {
          const {tid,sid,uid,data} = props ?? {};

          return  deleteApiV1TenantsTidSpacesSidMembersUid(tid,sid,uid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1TenantsTidSpacesSidMembersUidMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSidMembersUid>>>
    export type DeleteApiV1TenantsTidSpacesSidMembersUidMutationBody = DeleteApiV1TenantsTidSpacesSidMembersUidBody
    export type DeleteApiV1TenantsTidSpacesSidMembersUidMutationError = ErrorType<Error>
    export type DeleteApiV1TenantsTidSpacesSidMembersUidMutationVariables = {tid: string;sid: string;uid: string;data: DeleteApiV1TenantsTidSpacesSidMembersUidBody}

    /**
 * @summary DELETE /api/v1/tenants/:tid/spaces/:sid/members/:uid
 */
export const useDeleteApiV1TenantsTidSpacesSidMembersUid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSidMembersUid>>, TError,DeleteApiV1TenantsTidSpacesSidMembersUidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSidMembersUid>>,
        TError,
        DeleteApiV1TenantsTidSpacesSidMembersUidMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1TenantsTidSpacesSidMembersUidMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Updates a member's role (admin/member/owner) or status; admin or owner, and granting owner requires owner. The target user must be an active member of the same tenant; a matching version is required. The last owner cannot be demoted or disabled (409 space_last_owner). Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PUT /api/v1/tenants/:tid/spaces/:sid/members/:uid
 */
export const putApiV1TenantsTidSpacesSidMembersUid = (
    tid: string,
    sid: string,
    uid: string,
    putApiV1TenantsTidSpacesSidMembersUidBody: PutApiV1TenantsTidSpacesSidMembersUidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SpaceMember>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}/members/${uid}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV1TenantsTidSpacesSidMembersUidBody, signal
    },
      options);
    }




export const getPutApiV1TenantsTidSpacesSidMembersUidMutationKey = () => ['putApiV1TenantsTidSpacesSidMembersUid'] as const;

export const getPutApiV1TenantsTidSpacesSidMembersUidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSidMembersUid>>, TError,PutApiV1TenantsTidSpacesSidMembersUidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSidMembersUid>>, TError,PutApiV1TenantsTidSpacesSidMembersUidMutationVariables, TContext> => {

const mutationKey = getPutApiV1TenantsTidSpacesSidMembersUidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSidMembersUid>>, PutApiV1TenantsTidSpacesSidMembersUidMutationVariables> = (props) => {
          const {tid,sid,uid,data} = props ?? {};

          return  putApiV1TenantsTidSpacesSidMembersUid(tid,sid,uid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1TenantsTidSpacesSidMembersUidMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSidMembersUid>>>
    export type PutApiV1TenantsTidSpacesSidMembersUidMutationBody = PutApiV1TenantsTidSpacesSidMembersUidBody
    export type PutApiV1TenantsTidSpacesSidMembersUidMutationError = ErrorType<Error>
    export type PutApiV1TenantsTidSpacesSidMembersUidMutationVariables = {tid: string;sid: string;uid: string;data: PutApiV1TenantsTidSpacesSidMembersUidBody}

    /**
 * @summary PUT /api/v1/tenants/:tid/spaces/:sid/members/:uid
 */
export const usePutApiV1TenantsTidSpacesSidMembersUid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSidMembersUid>>, TError,PutApiV1TenantsTidSpacesSidMembersUidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSidMembersUid>>,
        TError,
        PutApiV1TenantsTidSpacesSidMembersUidMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiV1TenantsTidSpacesSidMembersUidMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Project collection scoped to one collaboration space; membership is required, and project visibility follows workspace membership — any active member of the space can see every active project in it. Deleting a project requires its creator or a space owner/admin. spaceId on a created project is optional, never forced. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:sid/projects
 */
export const getApiV1TenantsTidSpacesSidProjects = (
    tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidProjectsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidSpacesSidProjects200>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}/projects`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSidProjectsQueryKey = (tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidProjectsParams,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${sid}/projects`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSidProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError = ErrorType<Error>>(tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSidProjectsQueryKey(tid,sid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>> = ({ signal }) => getApiV1TenantsTidSpacesSidProjects(tid,sid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && sid !== null && sid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSidProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>>
export type GetApiV1TenantsTidSpacesSidProjectsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSidProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string,
    params: undefined |  GetApiV1TenantsTidSpacesSidProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSidProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSidProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:sid/projects
 */

export function useGetApiV1TenantsTidSpacesSidProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError = ErrorType<Error>>(
 tid: string,
    sid: string,
    params?: GetApiV1TenantsTidSpacesSidProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSidProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSidProjectsQueryOptions(tid,sid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Project collection scoped to one collaboration space; membership is required, and project visibility follows workspace membership — any active member of the space can see every active project in it. Deleting a project requires its creator or a space owner/admin. spaceId on a created project is optional, never forced. Creates Project/storage/main Workspace/operation atomically. repositoryUrl allows HTTPS or SSH with no password/query/fragment. defaultBranch defaults to HEAD; credentialRefId must belong to tenant and owner. Storage/worktree/sandbox initialization is asynchronous. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/spaces/:sid/projects
 */
export const postApiV1TenantsTidSpacesSidProjects = (
    tid: string,
    sid: string,
    postApiV1TenantsTidSpacesSidProjectsBody: PostApiV1TenantsTidSpacesSidProjectsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidSpacesSidProjects202>(
      {url: `/api/v1/tenants/${tid}/spaces/${sid}/projects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidSpacesSidProjectsBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidSpacesSidProjectsMutationKey = () => ['postApiV1TenantsTidSpacesSidProjects'] as const;

export const getPostApiV1TenantsTidSpacesSidProjectsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidProjects>>, TError,PostApiV1TenantsTidSpacesSidProjectsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidProjects>>, TError,PostApiV1TenantsTidSpacesSidProjectsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidSpacesSidProjectsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidProjects>>, PostApiV1TenantsTidSpacesSidProjectsMutationVariables> = (props) => {
          const {tid,sid,data} = props ?? {};

          return  postApiV1TenantsTidSpacesSidProjects(tid,sid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidSpacesSidProjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidProjects>>>
    export type PostApiV1TenantsTidSpacesSidProjectsMutationBody = PostApiV1TenantsTidSpacesSidProjectsBody
    export type PostApiV1TenantsTidSpacesSidProjectsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidSpacesSidProjectsMutationVariables = {tid: string;sid: string;data: PostApiV1TenantsTidSpacesSidProjectsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/spaces/:sid/projects
 */
export const usePostApiV1TenantsTidSpacesSidProjects = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidProjects>>, TError,PostApiV1TenantsTidSpacesSidProjectsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSidProjects>>,
        TError,
        PostApiV1TenantsTidSpacesSidProjectsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidSpacesSidProjectsMutationOptions(options), queryClient);
    }
