/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Agent,
  AgentSkillBinding,
  DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody,
  DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody,
  Error,
  GetApiV1TenantsTidSpacesSpaceIdAgents200,
  GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills200,
  GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsParams,
  GetApiV1TenantsTidSpacesSpaceIdAgentsParams,
  PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody,
  PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsBody,
  PostApiV1TenantsTidSpacesSpaceIdAgentsBody,
  PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Reads an Agent or lists the workspace's live Agents; any active member can read. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/agents
 */
export const getApiV1TenantsTidSpacesSpaceIdAgents = (
    tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidSpacesSpaceIdAgents200>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSpaceIdAgentsQueryKey = (tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsParams,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}/agents`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSpaceIdAgentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSpaceIdAgentsQueryKey(tid,spaceId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>> = ({ signal }) => getApiV1TenantsTidSpacesSpaceIdAgents(tid,spaceId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSpaceIdAgentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>>
export type GetApiV1TenantsTidSpacesSpaceIdAgentsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSpaceIdAgents<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params: undefined |  GetApiV1TenantsTidSpacesSpaceIdAgentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdAgents<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdAgents<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/agents
 */

export function useGetApiV1TenantsTidSpacesSpaceIdAgents<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSpaceIdAgentsQueryOptions(tid,spaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Creates an Agent owned by the Collaboration Workspace. Active names are unique within the workspace. Requires owner/admin and an idempotency key. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/agents
 */
export const postApiV1TenantsTidSpacesSpaceIdAgents = (
    tid: string,
    spaceId: string,
    postApiV1TenantsTidSpacesSpaceIdAgentsBody: PostApiV1TenantsTidSpacesSpaceIdAgentsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Agent>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidSpacesSpaceIdAgentsBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidSpacesSpaceIdAgentsMutationKey = () => ['postApiV1TenantsTidSpacesSpaceIdAgents'] as const;

export const getPostApiV1TenantsTidSpacesSpaceIdAgentsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgents>>, TError,PostApiV1TenantsTidSpacesSpaceIdAgentsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgents>>, TError,PostApiV1TenantsTidSpacesSpaceIdAgentsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidSpacesSpaceIdAgentsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgents>>, PostApiV1TenantsTidSpacesSpaceIdAgentsMutationVariables> = (props) => {
          const {tid,spaceId,data} = props ?? {};

          return  postApiV1TenantsTidSpacesSpaceIdAgents(tid,spaceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidSpacesSpaceIdAgentsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgents>>>
    export type PostApiV1TenantsTidSpacesSpaceIdAgentsMutationBody = PostApiV1TenantsTidSpacesSpaceIdAgentsBody
    export type PostApiV1TenantsTidSpacesSpaceIdAgentsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidSpacesSpaceIdAgentsMutationVariables = {tid: string;spaceId: string;data: PostApiV1TenantsTidSpacesSpaceIdAgentsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/agents
 */
export const usePostApiV1TenantsTidSpacesSpaceIdAgents = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgents>>, TError,PostApiV1TenantsTidSpacesSpaceIdAgentsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgents>>,
        TError,
        PostApiV1TenantsTidSpacesSpaceIdAgentsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidSpacesSpaceIdAgentsMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Archives the space (soft delete); requires owner and a matching version. The default space cannot be archived. Projects are unaffected. Soft-deletes an Agent; the creator or a workspace owner/admin may delete. A soft-deleted Agent denies new executions while historical state is preserved. Requires a matching version and an idempotency key. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary DELETE /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId
 */
export const deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId = (
    tid: string,
    spaceId: string,
    agentId: string,
    deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody: DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Agent>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody, signal
    },
      options);
    }




export const getDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationKey = () => ['deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId'] as const;

export const getDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables> = (props) => {
          const {tid,spaceId,agentId,data} = props ?? {};

          return  deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId(tid,spaceId,agentId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>>
    export type DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationBody = DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody
    export type DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationError = ErrorType<Error>
    export type DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables = {tid: string;spaceId: string;agentId: string;data: DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody}

    /**
 * @summary DELETE /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId
 */
export const useDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>,
        TError,
        DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Reads an Agent or lists the workspace's live Agents; any active member can read. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId
 */
export const getApiV1TenantsTidSpacesSpaceIdAgentsAgentId = (
    tid: string,
    spaceId: string,
    agentId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Agent>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdQueryKey = (tid: string,
    spaceId: string,
    agentId: string,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}`
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string,
    agentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdQueryKey(tid,spaceId,agentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>> = ({ signal }) => getApiV1TenantsTidSpacesSpaceIdAgentsAgentId(tid,spaceId,agentId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined && agentId !== null && agentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>>
export type GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSpaceIdAgentsAgentId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    agentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdAgentsAgentId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    agentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdAgentsAgentId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    agentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId
 */

export function useGetApiV1TenantsTidSpacesSpaceIdAgentsAgentId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    agentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdQueryOptions(tid,spaceId,agentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only name and description may change; slug is immutable. Requires admin or owner and a matching version. Updates an Agent's name and/or status (active|disabled); omitted fields keep their current value. Requires owner/admin and a matching version. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PATCH /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId
 */
export const patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId = (
    tid: string,
    spaceId: string,
    agentId: string,
    patchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody: PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Agent>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody, signal
    },
      options);
    }




export const getPatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationKey = () => ['patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId'] as const;

export const getPatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError,PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError,PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables, TContext> => {

const mutationKey = getPatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables> = (props) => {
          const {tid,spaceId,agentId,data} = props ?? {};

          return  patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId(tid,spaceId,agentId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>>
    export type PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationBody = PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody
    export type PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationError = ErrorType<Error>
    export type PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables = {tid: string;spaceId: string;agentId: string;data: PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdBody}

    /**
 * @summary PATCH /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId
 */
export const usePatchApiV1TenantsTidSpacesSpaceIdAgentsAgentId = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>, TError,PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1TenantsTidSpacesSpaceIdAgentsAgentId>>,
        TError,
        PatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiV1TenantsTidSpacesSpaceIdAgentsAgentIdMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Lists an Agent's bindings, including bindings to soft-deleted Skills so stale configuration stays observable. Any active member can read. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId/skills
 */
export const getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills = (
    tid: string,
    spaceId: string,
    agentId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills200>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}/skills`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsQueryKey = (tid: string,
    spaceId: string,
    agentId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsParams,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}/skills`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string,
    agentId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsQueryKey(tid,spaceId,agentId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>> = ({ signal }) => getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills(tid,spaceId,agentId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined && agentId !== null && agentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>>
export type GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    agentId: string,
    params: undefined |  GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    agentId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    agentId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId/skills
 */

export function useGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    agentId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsQueryOptions(tid,spaceId,agentId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Attaches a Skill's business identity to an Agent as an enabled binding; the Skill must be live and in the same Collaboration Workspace (a cross-workspace or soft-deleted Skill is 404). A duplicate (agent, skill) is 409 binding_exists. Requires owner/admin and an idempotency key; the binding references identity only, never a specific revision. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId/skills
 */
export const postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills = (
    tid: string,
    spaceId: string,
    agentId: string,
    postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsBody: PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AgentSkillBinding>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}/skills`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationKey = () => ['postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills'] as const;

export const getPostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError,PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError,PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationVariables> = (props) => {
          const {tid,spaceId,agentId,data} = props ?? {};

          return  postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills(tid,spaceId,agentId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>>
    export type PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationBody = PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsBody
    export type PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationVariables = {tid: string;spaceId: string;agentId: string;data: PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId/skills
 */
export const usePostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>, TError,PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkills>>,
        TError,
        PostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Archives the space (soft delete); requires owner and a matching version. The default space cannot be archived. Projects are unaffected. Detaches a Skill from an Agent (hard delete; no version). An absent binding is 404 binding_not_found; a matching idempotency key replays the original detach. Requires owner/admin. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary DELETE /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId/skills/:skillId
 */
export const deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId = (
    tid: string,
    spaceId: string,
    agentId: string,
    skillId: string,
    deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody: DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AgentSkillBinding>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}/skills/${skillId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody, signal
    },
      options);
    }




export const getDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationKey = () => ['deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId'] as const;

export const getDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>, DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables> = (props) => {
          const {tid,spaceId,agentId,skillId,data} = props ?? {};

          return  deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId(tid,spaceId,agentId,skillId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>>
    export type DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationBody = DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody
    export type DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationError = ErrorType<Error>
    export type DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables = {tid: string;spaceId: string;agentId: string;skillId: string;data: DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody}

    /**
 * @summary DELETE /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId/skills/:skillId
 */
export const useDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>,
        TError,
        DeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Enables or disables one binding (enabled=true/false); enabled must be present. A disabled binding remains configuration but is excluded from future execution selection. Requires owner/admin and a matching version. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PUT /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId/skills/:skillId
 */
export const putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId = (
    tid: string,
    spaceId: string,
    agentId: string,
    skillId: string,
    putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody: PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AgentSkillBinding>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/agents/${agentId}/skills/${skillId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody, signal
    },
      options);
    }




export const getPutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationKey = () => ['putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId'] as const;

export const getPutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>, TError,PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>, TError,PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables, TContext> => {

const mutationKey = getPutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>, PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables> = (props) => {
          const {tid,spaceId,agentId,skillId,data} = props ?? {};

          return  putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId(tid,spaceId,agentId,skillId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>>
    export type PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationBody = PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody
    export type PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationError = ErrorType<Error>
    export type PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables = {tid: string;spaceId: string;agentId: string;skillId: string;data: PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdBody}

    /**
 * @summary PUT /api/v1/tenants/:tid/spaces/:spaceId/agents/:agentId/skills/:skillId
 */
export const usePutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>, TError,PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillId>>,
        TError,
        PutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiV1TenantsTidSpacesSpaceIdAgentsAgentIdSkillsSkillIdMutationOptions(options), queryClient);
    }
