/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetApiV1TenantsTidMembers200,
  GetApiV1TenantsTidMembersParams,
  Member,
  PutApiV1TenantsTidMembersUidBody
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Administrator only. Updating an existing membership requires matching version; new membership uses version=0. Last effective administrator cannot be disabled/demoted, including concurrent changes. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/members
 */
export const getApiV1TenantsTidMembers = (
    tid: string,
    params?: GetApiV1TenantsTidMembersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidMembers200>(
      {url: `/api/v1/tenants/${tid}/members`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidMembersQueryKey = (tid: string,
    params?: GetApiV1TenantsTidMembersParams,) => {
    return [
    `/api/v1/tenants/${tid}/members`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidMembersQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError = ErrorType<Error>>(tid: string,
    params?: GetApiV1TenantsTidMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidMembersQueryKey(tid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>> = ({ signal }) => getApiV1TenantsTidMembers(tid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidMembersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>>
export type GetApiV1TenantsTidMembersQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidMembers<TData = Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError = ErrorType<Error>>(
 tid: string,
    params: undefined |  GetApiV1TenantsTidMembersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidMembers<TData = Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidMembers<TData = Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/members
 */

export function useGetApiV1TenantsTidMembers<TData = Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidMembersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidMembersQueryOptions(tid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Administrator only. Updating an existing membership requires matching version; new membership uses version=0. Last effective administrator cannot be disabled/demoted, including concurrent changes. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PUT /api/v1/tenants/:tid/members/:uid
 */
export const putApiV1TenantsTidMembersUid = (
    tid: string,
    uid: string,
    putApiV1TenantsTidMembersUidBody: PutApiV1TenantsTidMembersUidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Member>(
      {url: `/api/v1/tenants/${tid}/members/${uid}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV1TenantsTidMembersUidBody, signal
    },
      options);
    }




export const getPutApiV1TenantsTidMembersUidMutationKey = () => ['putApiV1TenantsTidMembersUid'] as const;

export const getPutApiV1TenantsTidMembersUidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidMembersUid>>, TError,PutApiV1TenantsTidMembersUidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidMembersUid>>, TError,PutApiV1TenantsTidMembersUidMutationVariables, TContext> => {

const mutationKey = getPutApiV1TenantsTidMembersUidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1TenantsTidMembersUid>>, PutApiV1TenantsTidMembersUidMutationVariables> = (props) => {
          const {tid,uid,data} = props ?? {};

          return  putApiV1TenantsTidMembersUid(tid,uid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1TenantsTidMembersUidMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1TenantsTidMembersUid>>>
    export type PutApiV1TenantsTidMembersUidMutationBody = PutApiV1TenantsTidMembersUidBody
    export type PutApiV1TenantsTidMembersUidMutationError = ErrorType<Error>
    export type PutApiV1TenantsTidMembersUidMutationVariables = {tid: string;uid: string;data: PutApiV1TenantsTidMembersUidBody}

    /**
 * @summary PUT /api/v1/tenants/:tid/members/:uid
 */
export const usePutApiV1TenantsTidMembersUid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1TenantsTidMembersUid>>, TError,PutApiV1TenantsTidMembersUidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1TenantsTidMembersUid>>,
        TError,
        PutApiV1TenantsTidMembersUidMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiV1TenantsTidMembersUidMutationOptions(options), queryClient);
    }
