/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminOperation,
  Error,
  Operation,
  PostApiV1TenantsTidOperationsOidRetry202,
  PostApiV1TenantsTidOperationsOidRetryBody
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Operation lookup follows project owner; administrative-stop actor receives only the restricted projection. Retry only accepts blocked/retry_wait, exact operation version, and an idempotency key. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/operations/:oid
 */
export const getApiV1TenantsTidOperationsOid = (
    tid: string,
    oid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Operation | AdminOperation>(
      {url: `/api/v1/tenants/${tid}/operations/${oid}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidOperationsOidQueryKey = (tid: string,
    oid: string,) => {
    return [
    `/api/v1/tenants/${tid}/operations/${oid}`
    ] as const;
    }


export const getGetApiV1TenantsTidOperationsOidQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError = ErrorType<Error>>(tid: string,
    oid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidOperationsOidQueryKey(tid,oid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>> = ({ signal }) => getApiV1TenantsTidOperationsOid(tid,oid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && oid !== null && oid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidOperationsOidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>>
export type GetApiV1TenantsTidOperationsOidQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidOperationsOid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError = ErrorType<Error>>(
 tid: string,
    oid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidOperationsOid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError = ErrorType<Error>>(
 tid: string,
    oid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidOperationsOid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError = ErrorType<Error>>(
 tid: string,
    oid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/operations/:oid
 */

export function useGetApiV1TenantsTidOperationsOid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError = ErrorType<Error>>(
 tid: string,
    oid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidOperationsOid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidOperationsOidQueryOptions(tid,oid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Operation lookup follows project owner; administrative-stop actor receives only the restricted projection. Retry only accepts blocked/retry_wait, exact operation version, and an idempotency key. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/operations/:oid/retry
 */
export const postApiV1TenantsTidOperationsOidRetry = (
    tid: string,
    oid: string,
    postApiV1TenantsTidOperationsOidRetryBody: PostApiV1TenantsTidOperationsOidRetryBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidOperationsOidRetry202>(
      {url: `/api/v1/tenants/${tid}/operations/${oid}/retry`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidOperationsOidRetryBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidOperationsOidRetryMutationKey = () => ['postApiV1TenantsTidOperationsOidRetry'] as const;

export const getPostApiV1TenantsTidOperationsOidRetryMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidOperationsOidRetry>>, TError,PostApiV1TenantsTidOperationsOidRetryMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidOperationsOidRetry>>, TError,PostApiV1TenantsTidOperationsOidRetryMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidOperationsOidRetryMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidOperationsOidRetry>>, PostApiV1TenantsTidOperationsOidRetryMutationVariables> = (props) => {
          const {tid,oid,data} = props ?? {};

          return  postApiV1TenantsTidOperationsOidRetry(tid,oid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidOperationsOidRetryMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidOperationsOidRetry>>>
    export type PostApiV1TenantsTidOperationsOidRetryMutationBody = PostApiV1TenantsTidOperationsOidRetryBody
    export type PostApiV1TenantsTidOperationsOidRetryMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidOperationsOidRetryMutationVariables = {tid: string;oid: string;data: PostApiV1TenantsTidOperationsOidRetryBody}

    /**
 * @summary POST /api/v1/tenants/:tid/operations/:oid/retry
 */
export const usePostApiV1TenantsTidOperationsOidRetry = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidOperationsOidRetry>>, TError,PostApiV1TenantsTidOperationsOidRetryMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidOperationsOidRetry>>,
        TError,
        PostApiV1TenantsTidOperationsOidRetryMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidOperationsOidRetryMutationOptions(options), queryClient);
    }
