/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdBody,
  Error,
  GetApiV1TenantsTidSpacesSpaceIdSkills200,
  GetApiV1TenantsTidSpacesSpaceIdSkillsParams,
  PostApiV1TenantsTidSpacesSpaceIdSkillsImportsBody,
  Skill,
  SourceUploadResult
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Lists the workspace's live Skills in deterministic (canonical_name, skill id) order with UUID pagination; any active member can read. Only public identity and current-revision fields are returned — never the object storage locator, bucket, storage key, provider, or any signed URL. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/skills
 */
export const getApiV1TenantsTidSpacesSpaceIdSkills = (
    tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdSkillsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidSpacesSpaceIdSkills200>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/skills`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSpaceIdSkillsQueryKey = (tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdSkillsParams,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}/skills`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSpaceIdSkillsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdSkillsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSpaceIdSkillsQueryKey(tid,spaceId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>> = ({ signal }) => getApiV1TenantsTidSpacesSpaceIdSkills(tid,spaceId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSpaceIdSkillsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>>
export type GetApiV1TenantsTidSpacesSpaceIdSkillsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSpaceIdSkills<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params: undefined |  GetApiV1TenantsTidSpacesSpaceIdSkillsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdSkills<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdSkillsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdSkills<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdSkillsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/skills
 */

export function useGetApiV1TenantsTidSpacesSpaceIdSkills<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    params?: GetApiV1TenantsTidSpacesSpaceIdSkillsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkills>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSpaceIdSkillsQueryOptions(tid,spaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Imports a Skill source as one archive (zip or uncompressed tar) via multipart/form-data. source_kind selects the decoder (no filename/MIME sniffing); the archive is decoded into deterministic candidates and ingested through the journal-first saga under the Idempotency-Key as the saga idempotency namespace (same key + same fingerprint replays or resumes; a different fingerprint is 409). Requires space owner/admin; a non-member or a cross-space target_skill_id is 404 not_found. Returns a 200 envelope with preparationFailures and per-candidate ingestions; a source-level structural failure (zero candidates) is 400 with a source_* code. The body budget is 256 MiB (413 upload_too_large).
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/skills/imports
 */
export const postApiV1TenantsTidSpacesSpaceIdSkillsImports = (
    tid: string,
    spaceId: string,
    postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody: PostApiV1TenantsTidSpacesSpaceIdSkillsImportsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {

      const formData = new FormData();
if(postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody.display_name !== undefined) {
 formData.append(`display_name`, postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody.display_name);
 }
formData.append(`source`, postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody.source);
formData.append(`source_kind`, postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody.source_kind);
if(postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody.summary !== undefined) {
 formData.append(`summary`, postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody.summary);
 }
if(postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody.target_skill_id !== undefined) {
 formData.append(`target_skill_id`, postApiV1TenantsTidSpacesSpaceIdSkillsImportsBody.target_skill_id);
 }

      return customInstance<SourceUploadResult>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/skills/imports`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }




export const getPostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationKey = () => ['postApiV1TenantsTidSpacesSpaceIdSkillsImports'] as const;

export const getPostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdSkillsImports>>, TError,PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdSkillsImports>>, TError,PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdSkillsImports>>, PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationVariables> = (props) => {
          const {tid,spaceId,data} = props ?? {};

          return  postApiV1TenantsTidSpacesSpaceIdSkillsImports(tid,spaceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdSkillsImports>>>
    export type PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationBody = PostApiV1TenantsTidSpacesSpaceIdSkillsImportsBody
    export type PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationVariables = {tid: string;spaceId: string;data: PostApiV1TenantsTidSpacesSpaceIdSkillsImportsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/spaces/:spaceId/skills/imports
 */
export const usePostApiV1TenantsTidSpacesSpaceIdSkillsImports = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdSkillsImports>>, TError,PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidSpacesSpaceIdSkillsImports>>,
        TError,
        PostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidSpacesSpaceIdSkillsImportsMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Archives the space (soft delete); requires owner and a matching version. The default space cannot be archived. Projects are unaffected. Soft-deletes a Skill; the creator or a workspace owner/admin may delete. The Skill disappears from the live list and future execution admission, but its SkillRevisions, object storage package, and any historical ExecutionSkillBinding snapshot are preserved, so a frozen Execution bound to this Skill's revision stays readable. Requires a matching version and an idempotency key. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary DELETE /api/v1/tenants/:tid/spaces/:spaceId/skills/:skillId
 */
export const deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId = (
    tid: string,
    spaceId: string,
    skillId: string,
    deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdBody: DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Skill>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/skills/${skillId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdBody, signal
    },
      options);
    }




export const getDeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationKey = () => ['deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId'] as const;

export const getDeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationVariables> = (props) => {
          const {tid,spaceId,skillId,data} = props ?? {};

          return  deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId(tid,spaceId,skillId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>>
    export type DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationBody = DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdBody
    export type DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationError = ErrorType<Error>
    export type DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationVariables = {tid: string;spaceId: string;skillId: string;data: DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdBody}

    /**
 * @summary DELETE /api/v1/tenants/:tid/spaces/:spaceId/skills/:skillId
 */
export const useDeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError,DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>,
        TError,
        DeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1TenantsTidSpacesSpaceIdSkillsSkillIdMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only joined members can read a space. Reads one live Skill's public identity and current revision; any active member can read. A soft-deleted or foreign-workspace Skill is 404 (no existence leak); storage credentials and locators are never exposed. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/skills/:skillId
 */
export const getApiV1TenantsTidSpacesSpaceIdSkillsSkillId = (
    tid: string,
    spaceId: string,
    skillId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Skill>(
      {url: `/api/v1/tenants/${tid}/spaces/${spaceId}/skills/${skillId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidSpacesSpaceIdSkillsSkillIdQueryKey = (tid: string,
    spaceId: string,
    skillId: string,) => {
    return [
    `/api/v1/tenants/${tid}/spaces/${spaceId}/skills/${skillId}`
    ] as const;
    }


export const getGetApiV1TenantsTidSpacesSpaceIdSkillsSkillIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError = ErrorType<Error>>(tid: string,
    spaceId: string,
    skillId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidSpacesSpaceIdSkillsSkillIdQueryKey(tid,spaceId,skillId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>> = ({ signal }) => getApiV1TenantsTidSpacesSpaceIdSkillsSkillId(tid,spaceId,skillId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && spaceId !== null && spaceId !== undefined && skillId !== null && skillId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidSpacesSpaceIdSkillsSkillIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>>
export type GetApiV1TenantsTidSpacesSpaceIdSkillsSkillIdQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidSpacesSpaceIdSkillsSkillId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    skillId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdSkillsSkillId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    skillId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidSpacesSpaceIdSkillsSkillId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    skillId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/spaces/:spaceId/skills/:skillId
 */

export function useGetApiV1TenantsTidSpacesSpaceIdSkillsSkillId<TData = Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError = ErrorType<Error>>(
 tid: string,
    spaceId: string,
    skillId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidSpacesSpaceIdSkillsSkillId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidSpacesSpaceIdSkillsSkillIdQueryOptions(tid,spaceId,skillId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






