/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV1TenantsTidProjectsPid202,
  DeleteApiV1TenantsTidProjectsPidBody,
  Error,
  GetApiV1TenantsTidProjects200,
  GetApiV1TenantsTidProjectsParams,
  PatchApiV1TenantsTidProjectsPidBody,
  PostApiV1TenantsTidProjects202,
  PostApiV1TenantsTidProjectsBody,
  Project
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/projects
 */
export const getApiV1TenantsTidProjects = (
    tid: string,
    params?: GetApiV1TenantsTidProjectsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1TenantsTidProjects200>(
      {url: `/api/v1/tenants/${tid}/projects`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1TenantsTidProjectsQueryKey = (tid: string,
    params?: GetApiV1TenantsTidProjectsParams,) => {
    return [
    `/api/v1/tenants/${tid}/projects`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1TenantsTidProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError = ErrorType<Error>>(tid: string,
    params?: GetApiV1TenantsTidProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidProjectsQueryKey(tid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>> = ({ signal }) => getApiV1TenantsTidProjects(tid,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>>
export type GetApiV1TenantsTidProjectsQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError = ErrorType<Error>>(
 tid: string,
    params: undefined |  GetApiV1TenantsTidProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/projects
 */

export function useGetApiV1TenantsTidProjects<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError = ErrorType<Error>>(
 tid: string,
    params?: GetApiV1TenantsTidProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidProjectsQueryOptions(tid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Creates Project/storage/main Workspace/operation atomically. repositoryUrl allows HTTPS or SSH with no password/query/fragment. defaultBranch defaults to HEAD; credentialRefId must belong to tenant and owner. Storage/worktree/sandbox initialization is asynchronous. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary POST /api/v1/tenants/:tid/projects
 */
export const postApiV1TenantsTidProjects = (
    tid: string,
    postApiV1TenantsTidProjectsBody: PostApiV1TenantsTidProjectsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PostApiV1TenantsTidProjects202>(
      {url: `/api/v1/tenants/${tid}/projects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1TenantsTidProjectsBody, signal
    },
      options);
    }




export const getPostApiV1TenantsTidProjectsMutationKey = () => ['postApiV1TenantsTidProjects'] as const;

export const getPostApiV1TenantsTidProjectsMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidProjects>>, TError,PostApiV1TenantsTidProjectsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidProjects>>, TError,PostApiV1TenantsTidProjectsMutationVariables, TContext> => {

const mutationKey = getPostApiV1TenantsTidProjectsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TenantsTidProjects>>, PostApiV1TenantsTidProjectsMutationVariables> = (props) => {
          const {tid,data} = props ?? {};

          return  postApiV1TenantsTidProjects(tid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TenantsTidProjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TenantsTidProjects>>>
    export type PostApiV1TenantsTidProjectsMutationBody = PostApiV1TenantsTidProjectsBody
    export type PostApiV1TenantsTidProjectsMutationError = ErrorType<Error>
    export type PostApiV1TenantsTidProjectsMutationVariables = {tid: string;data: PostApiV1TenantsTidProjectsBody}

    /**
 * @summary POST /api/v1/tenants/:tid/projects
 */
export const usePostApiV1TenantsTidProjects = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TenantsTidProjects>>, TError,PostApiV1TenantsTidProjectsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TenantsTidProjects>>,
        TError,
        PostApiV1TenantsTidProjectsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV1TenantsTidProjectsMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Requires matching resource version and no active project operation. Atomically closes new execution admission. Active tickets return 409 resource_in_use without changing admission. Unknown Node activity requires later proof and remains pending/blocked. main Workspace cannot be independently deleted. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary DELETE /api/v1/tenants/:tid/projects/:pid
 */
export const deleteApiV1TenantsTidProjectsPid = (
    tid: string,
    pid: string,
    deleteApiV1TenantsTidProjectsPidBody: DeleteApiV1TenantsTidProjectsPidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DeleteApiV1TenantsTidProjectsPid202>(
      {url: `/api/v1/tenants/${tid}/projects/${pid}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1TenantsTidProjectsPidBody, signal
    },
      options);
    }




export const getDeleteApiV1TenantsTidProjectsPidMutationKey = () => ['deleteApiV1TenantsTidProjectsPid'] as const;

export const getDeleteApiV1TenantsTidProjectsPidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidProjectsPid>>, TError,DeleteApiV1TenantsTidProjectsPidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidProjectsPid>>, TError,DeleteApiV1TenantsTidProjectsPidMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1TenantsTidProjectsPidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1TenantsTidProjectsPid>>, DeleteApiV1TenantsTidProjectsPidMutationVariables> = (props) => {
          const {tid,pid,data} = props ?? {};

          return  deleteApiV1TenantsTidProjectsPid(tid,pid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1TenantsTidProjectsPidMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1TenantsTidProjectsPid>>>
    export type DeleteApiV1TenantsTidProjectsPidMutationBody = DeleteApiV1TenantsTidProjectsPidBody
    export type DeleteApiV1TenantsTidProjectsPidMutationError = ErrorType<Error>
    export type DeleteApiV1TenantsTidProjectsPidMutationVariables = {tid: string;pid: string;data: DeleteApiV1TenantsTidProjectsPidBody}

    /**
 * @summary DELETE /api/v1/tenants/:tid/projects/:pid
 */
export const useDeleteApiV1TenantsTidProjectsPid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1TenantsTidProjectsPid>>, TError,DeleteApiV1TenantsTidProjectsPidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1TenantsTidProjectsPid>>,
        TError,
        DeleteApiV1TenantsTidProjectsPidMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1TenantsTidProjectsPidMutationOptions(options), queryClient);
    }
    /**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/tenants/:tid/projects/:pid
 */
export const getApiV1TenantsTidProjectsPid = (
    tid: string,
    pid: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Project>(
      {url: `/api/v1/tenants/${tid}/projects/${pid}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1TenantsTidProjectsPidQueryKey = (tid: string,
    pid: string,) => {
    return [
    `/api/v1/tenants/${tid}/projects/${pid}`
    ] as const;
    }


export const getGetApiV1TenantsTidProjectsPidQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError = ErrorType<Error>>(tid: string,
    pid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TenantsTidProjectsPidQueryKey(tid,pid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>> = ({ signal }) => getApiV1TenantsTidProjectsPid(tid,pid, requestOptions, signal);





   return  { queryKey, queryFn, enabled: tid !== null && tid !== undefined && pid !== null && pid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TenantsTidProjectsPidQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>>
export type GetApiV1TenantsTidProjectsPidQueryError = ErrorType<Error>


export function useGetApiV1TenantsTidProjectsPid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError = ErrorType<Error>>(
 tid: string,
    pid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidProjectsPid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError = ErrorType<Error>>(
 tid: string,
    pid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TenantsTidProjectsPid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError = ErrorType<Error>>(
 tid: string,
    pid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/tenants/:tid/projects/:pid
 */

export function useGetApiV1TenantsTidProjectsPid<TData = Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError = ErrorType<Error>>(
 tid: string,
    pid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TenantsTidProjectsPid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TenantsTidProjectsPidQueryOptions(tid,pid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Tenant membership is checked before lookup; resource reads filter tenant in SQL, and space-scoped projects and their runtime workspaces additionally require active membership of that workspace, while unscoped projects stay owner-scoped. Only project name may change; version must match. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary PATCH /api/v1/tenants/:tid/projects/:pid
 */
export const patchApiV1TenantsTidProjectsPid = (
    tid: string,
    pid: string,
    patchApiV1TenantsTidProjectsPidBody: PatchApiV1TenantsTidProjectsPidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Project>(
      {url: `/api/v1/tenants/${tid}/projects/${pid}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchApiV1TenantsTidProjectsPidBody, signal
    },
      options);
    }




export const getPatchApiV1TenantsTidProjectsPidMutationKey = () => ['patchApiV1TenantsTidProjectsPid'] as const;

export const getPatchApiV1TenantsTidProjectsPidMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidProjectsPid>>, TError,PatchApiV1TenantsTidProjectsPidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidProjectsPid>>, TError,PatchApiV1TenantsTidProjectsPidMutationVariables, TContext> => {

const mutationKey = getPatchApiV1TenantsTidProjectsPidMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1TenantsTidProjectsPid>>, PatchApiV1TenantsTidProjectsPidMutationVariables> = (props) => {
          const {tid,pid,data} = props ?? {};

          return  patchApiV1TenantsTidProjectsPid(tid,pid,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1TenantsTidProjectsPidMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1TenantsTidProjectsPid>>>
    export type PatchApiV1TenantsTidProjectsPidMutationBody = PatchApiV1TenantsTidProjectsPidBody
    export type PatchApiV1TenantsTidProjectsPidMutationError = ErrorType<Error>
    export type PatchApiV1TenantsTidProjectsPidMutationVariables = {tid: string;pid: string;data: PatchApiV1TenantsTidProjectsPidBody}

    /**
 * @summary PATCH /api/v1/tenants/:tid/projects/:pid
 */
export const usePatchApiV1TenantsTidProjectsPid = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1TenantsTidProjectsPid>>, TError,PatchApiV1TenantsTidProjectsPidMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1TenantsTidProjectsPid>>,
        TError,
        PatchApiV1TenantsTidProjectsPidMutationVariables,
        TContext
      > => {
      return useMutation(getPatchApiV1TenantsTidProjectsPidMutationOptions(options), queryClient);
    }
